jbpm-console-ng-showcase/pom.xml
jbpm-console-ng-showcase/src/main/resources/org/jbpm/console/ng/jBPMShowcase.gwt.xml

Dependencies adjustment for datamodeller at jbpm-console-showcase.

JBPM-4625 Generation of JPA enabled models

---

jbpm-console-ng-workbench-integration/jbpm-console-ng-workbench-integration-backend/pom.xml
jbpm-console-ng-workbench-integration/jbpm-console-ng-workbench-integration-backend/src/main/java/org/jbpm/console/ng/wi/backend/server/dd/DDEditorServiceImpl.java

See https://issues.jboss.org/browse/GUVNOR-2204

GUVNOR-2204: HTML entities incorrectly used in kie-deployment-descriptor Source tab

---

jbpm-console-ng-showcase/pom.xml
jbpm-console-ng-showcase/src/main/java/org/jbpm/console/ng/client/ShowcaseEntryPoint.java
jbpm-console-ng-showcase/src/main/resources/org/jbpm/console/ng/jBPMShowcase.gwt.xml
jbpm-console-ng-showcase/src/main/webapp/jbpm-console.html

- Ace editor support was added
Editors like the deployment descriptor editor or the datamodeler doesn't work without the Ace editor support.
- Data modeller uberfire docks was added

Ace editor and UberfireDocks support added

---

jbpm-console-ng-dashboard/jbpm-console-ng-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/AbstractDashboard.java
jbpm-console-ng-dashboard/jbpm-console-ng-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/ProcessDashboard.java
jbpm-console-ng-dashboard/jbpm-console-ng-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/ProcessDashboardView.java
jbpm-console-ng-dashboard/jbpm-console-ng-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/ProcessDashboardView.ui.xml
jbpm-console-ng-dashboard/jbpm-console-ng-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/TaskDashboard.java
jbpm-console-ng-dashboard/jbpm-console-ng-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/TaskDashboardView.java
jbpm-console-ng-dashboard/jbpm-console-ng-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/TaskDashboardView.ui.xml
jbpm-console-ng-dashboard/jbpm-console-ng-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/widgets/DisplayerContainerView.ui.xml
jbpm-console-ng-dashboard/jbpm-console-ng-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/widgets/ProcessBreadCrumbView.ui.xml

Combined common code between Task and Process dashboard classes, avoiding code duplication
UI styles update, manly to allow content to be responsive

Dashboard updates

---

jbpm-console-ng-showcase/src/main/java/org/jbpm/console/ng/server/impl/LuceneConfigProducer.java

See also: 
- https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/169
- https://github.com/uberfire/uberfire/pull/337
- https://github.com/uberfire/uberfire-extensions/pull/258
- https://github.com/droolsjbpm/kie-wb-common/pull/337
- https://github.com/droolsjbpm/jbpm-designer/pull/220
- https://github.com/droolsjbpm/jbpm-form-modeler/pull/46
- https://github.com/droolsjbpm/jbpm-console-ng/pull/395
- https://github.com/droolsjbpm/drools-wb/pull/156
- https://github.com/droolsjbpm/kie-wb-distributions/pull/261

UF-295 - Upgrading lucene to 5.3.1

---

jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/tasklogs/TaskLogsPresenter.java
jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/test/java/org/jbpm/console/ng/ht/client/editors/tasklogs/TaskLogsPresenterTest.java

Unified format of audit log mesages displayed in TaskLogs tab + added unit test

Unify task logs messages format

---

jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-api/src/main/java/org/jbpm/console/ng/ht/service/TaskOperationsService.java
jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-backend/src/main/java/org/jbpm/console/ng/ht/backend/server/TaskOperationsServiceImpl.java
jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-backend/src/test/java/org/jbpm/console/ng/ht/backend/server/TaskOperationsServiceImplTest.java
jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskassignments/TaskAssignmentsPresenter.java
jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/test/java/org/jbpm/console/ng/ht/client/editors/taskassignments/TaskAssignmentsPresenterTest.java

Review logic to match task permission matrix where Task Initiator, Task Stakeholder, Potential Owner, Actual Owner and Business Administrator roles are allowed to delegate tasks.

BZ-1314589 - Review permission set for delegating tasks

---

jbpm-console-ng-business-domain/jbpm-console-ng-business-domain-backend/src/main/java/org/jbpm/console/ng/bd/backend/server/AdministrationServiceImpl.java

Ticket for this branch is here: https://bugzilla.redhat.com/show_bug.cgi?id=1316566
(cherry picked from commit 093b316f8a82e9c36d1c702cfa55a730f00b5aab)
https://github.com/droolsjbpm/guvnor/pull/286
https://github.com/droolsjbpm/kie-wb-common/pull/310
https://github.com/droolsjbpm/drools-wb/pull/144
https://github.com/droolsjbpm/jbpm-console-ng/pull/365
https://github.com/droolsjbpm/kie-wb-distributions/pull/229

[6.3.x] Bug 1316566 - User can not create projects in any other repository than master

---

jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskslist/grid/dash/DataSetTasksListGridViewImpl.java

Extracted 4x repeated task list filter tab setup code to 2 private methods. A lot can be done to de-duplicate the code in this class, but I'd rather proceed in smaller steps.
Also removed unused parameter "String role " from each of the 4 methods.

Extract duplicated code & remove unused parameter in DataSetTasksListGridViewImpl

---

jbpm-console-ng-generic/jbpm-console-ng-generic-forms-api/pom.xml
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-api/src/main/java/org/jbpm/console/ng/ga/forms/display/FormDisplayerConfig.java
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-api/src/main/java/org/jbpm/console/ng/ga/forms/display/view/FormContentResizeListener.java
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-client/pom.xml
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-client/src/main/java/org/jbpm/console/ng/gc/forms/client/display/GenericFormDisplayer.java
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-client/src/main/java/org/jbpm/console/ng/gc/forms/client/display/views/EmbeddedFormDisplayView.java
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-client/src/main/java/org/jbpm/console/ng/gc/forms/client/display/views/FormDisplayerView.java
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-client/src/main/java/org/jbpm/console/ng/gc/forms/client/display/views/GenericFormDisplayPresenter.java
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-client/src/main/java/org/jbpm/console/ng/gc/forms/client/display/views/GenericFormDisplayView.java
jbpm-console-ng-human-tasks-forms/jbpm-console-ng-human-tasks-forms-api/pom.xml
jbpm-console-ng-human-tasks-forms/jbpm-console-ng-human-tasks-forms-client/src/main/java/org/jbpm/console/ng/ht/forms/client/display/displayers/task/AbstractHumanTaskFormDisplayer.java
jbpm-console-ng-human-tasks-forms/jbpm-console-ng-human-tasks-forms-client/src/main/java/org/jbpm/console/ng/ht/forms/client/display/ht/api/HumanTaskFormDisplayProvider.java
jbpm-console-ng-human-tasks-forms/jbpm-console-ng-human-tasks-forms-client/src/main/java/org/jbpm/console/ng/ht/forms/client/display/ht/api/HumanTaskFormDisplayer.java
jbpm-console-ng-human-tasks-forms/jbpm-console-ng-human-tasks-forms-client/src/main/java/org/jbpm/console/ng/ht/forms/client/display/providers/HumanTaskFormDisplayProviderImpl.java
jbpm-console-ng-human-tasks-forms/jbpm-console-ng-human-tasks-forms-client/src/main/java/org/jbpm/console/ng/ht/forms/client/display/standalone/StandaloneTaskFormDisplayPresenter.java
jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskdetailsmulti/TaskDetailsMultiPresenter.java
jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskform/TaskFormPresenter.java
jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskform/TaskFormViewImpl.java
jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/test/java/org/jbpm/console/ng/ht/client/editors/taskdetailsmulti/TaskDetailsMultiPresenterTest.java
jbpm-console-ng-process-runtime-forms/jbpm-console-ng-process-runtime-forms-api/pom.xml
jbpm-console-ng-process-runtime-forms/jbpm-console-ng-process-runtime-forms-client/src/main/java/org/jbpm/console/ng/pr/forms/client/display/displayers/process/AbstractStartProcessFormDisplayer.java
jbpm-console-ng-process-runtime-forms/jbpm-console-ng-process-runtime-forms-client/src/main/java/org/jbpm/console/ng/pr/forms/client/display/process/api/StartProcessFormDisplayProvider.java
jbpm-console-ng-process-runtime-forms/jbpm-console-ng-process-runtime-forms-client/src/main/java/org/jbpm/console/ng/pr/forms/client/display/process/api/StartProcessFormDisplayer.java
jbpm-console-ng-process-runtime-forms/jbpm-console-ng-process-runtime-forms-client/src/main/java/org/jbpm/console/ng/pr/forms/client/display/providers/StartProcessFormDisplayProviderImpl.java
jbpm-console-ng-process-runtime-forms/jbpm-console-ng-process-runtime-forms-client/src/main/java/org/jbpm/console/ng/pr/forms/client/display/standalone/StandaloneProcessFormDisplayScreen.java
jbpm-console-ng-process-runtime-forms/jbpm-console-ng-process-runtime-forms-client/src/main/java/org/jbpm/console/ng/pr/forms/client/display/views/PopupFormDisplayerView.java
jbpm-console-ng-process-runtime-forms/jbpm-console-ng-process-runtime-forms-client/src/main/java/org/jbpm/console/ng/pr/forms/client/editors/quicknewinstance/QuickNewProcessInstancePopup.java
jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/pom.xml

Moved classes into client modules

Remove GWT dependent classes from API modules

---

jbpm-console-ng-showcase/pom.xml
jbpm-console-ng-showcase/src/main/webapp/WEB-INF/jboss-deployment-structure.xml

Reviewed dependencies on showcase app to better match kie-wb and avoid potential classloading issues/conflicts.
Reused jboss-deployment-structure.xml to also have a closer runtime classpath
Adjusted code format on showcase pom.xml

Showcase dependencies update

---

jbpm-console-ng-generic/jbpm-console-ng-generic-forms-client/pom.xml
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-client/src/main/java/org/jbpm/console/ng/gc/forms/client/GenericFormsClientEntryPoint.java
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-client/src/main/java/org/jbpm/console/ng/gc/forms/client/display/views/EmbeddedFormDisplayView.java
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-client/src/main/java/org/jbpm/console/ng/gc/forms/client/resources/AppResources.java
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-client/src/main/resources/org/jbpm/console/ng/gc/forms/JbpmConsoleNGGenericFormsClient.gwt.xml
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-client/src/main/resources/org/jbpm/console/ng/gc/forms/client/resources/css/forms.css
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-client/src/test/java/org/jbpm/console/ng/gc/forms/client/display/views/EmbeddedFormDisplayViewTest.java
jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskdetailsmulti/TaskDetailsMultiViewImpl.java
jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskform/TaskFormViewImpl.ui.xml

Put the form buttons in a fixed location leaving the form in a ScrollPanel.

BZ1301453 - Form is not fully shown for User Task in Task list.

---

jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskdetails/TaskDetailsPresenter.java
jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/test/java/org/jbpm/console/ng/ht/client/editors/taskdetails/TaskDetailsPresenterTest.java

Simple example for @bsremac  how to migrate tests to community. Please review and merge if acceptable.

Expand task details test coverage

---

jbpm-console-ng-business-domain/jbpm-console-ng-business-domain-client/src/main/java/org/jbpm/console/ng/bd/client/editors/deployment/list/NewDeploymentUnitMenuBuilder.java
jbpm-console-ng-generic/jbpm-console-ng-generic-client/src/main/java/org/jbpm/console/ng/gc/client/menu/RestoreDefaultFiltersMenuBuilder.java
jbpm-console-ng-showcase/src/main/java/org/jbpm/console/ng/client/ShowcaseEntryPoint.java
jbpm-console-ng-showcase/src/test/java/org/jbpm/console/ng/client/ShowcaseEntryPointTest.java

Changes required to support the new UF's security APIs
This PR depends on uberfire/uberfire#321

JBPM-5030: Access control based on the new UF's authz subsystem

---

jbpm-console-ng-executor-service/jbpm-console-ng-executor-service-client/src/main/java/org/jbpm/console/ng/es/client/editors/quicknewjob/QuickNewJobPopup.java
jbpm-console-ng-executor-service/jbpm-console-ng-executor-service-client/src/test/java/org/jbpm/console/ng/es/client/editors/quicknewjob/QuickNewJobPopupTest.java

Migrating Selenium tests to community.

Add new job modal validation tests

---

jbpm-console-ng-rest/src/main/java/org/jbpm/console/ng/rest/ProcessImageResourceImpl.java

Thanks for the reminder, @mswiderski

JBPM-5185 - HTTP 405 Error when retrieving process image via REST when running on WebSphere

---

jbpm-console-ng-rest/src/main/java/org/jbpm/console/ng/rest/ProcessImageResourceImpl.java
jbpm-console-ng-rest/src/test/java/org/jbpm/console/ng/rest/ProcessImageResourceTest.java

@mrietveld do you mind taking a look?

RHBPMS-4117 - jBPM UI - all passed nodes are marked as active

---

jbpm-console-ng-rest/src/main/java/org/jbpm/console/ng/rest/ProcessImageResourceImpl.java

6.4.x: RHBPMS-4135 - HTTP 404 Error when starting process via REST on WebLogic

---

jbpm-console-ng-showcase/pom.xml

Needs:
droolsjbpm/droolsjbpm-build-bootstrap#250
uberfire/uberfire#461
errai/errai#184

Upgrade to GWT 2.8.0-rc1

---

jbpm-console-ng-rest/src/main/java/org/jbpm/console/ng/rest/ProcessImageResourceImpl.java
jbpm-console-ng-rest/src/test/java/org/jbpm/console/ng/rest/JbpmConsoleNgRestBaseIntegrationTest.java
jbpm-console-ng-rest/src/test/java/org/jbpm/console/ng/rest/ProcessImageResourceTest.java

Related to the 6.3.3 GA release.

6.4.x: RHBPMS-4187 - process instance id not validated when getting process image

---

jbpm-console-ng-workbench-integration/jbpm-console-ng-workbench-integration-api/pom.xml
jbpm-console-ng-workbench-integration/jbpm-console-ng-workbench-integration-api/src/main/java/org/jbpm/console/ng/wi/cases/service/CaseProjectService.java
jbpm-console-ng-workbench-integration/jbpm-console-ng-workbench-integration-api/src/main/resources/org/jbpm/console/ng/wi/JbpmConsoleNGWorkbenchIntegrationAPI.gwt.xml
jbpm-console-ng-workbench-integration/jbpm-console-ng-workbench-integration-backend/pom.xml
jbpm-console-ng-workbench-integration/jbpm-console-ng-workbench-integration-backend/src/main/java/org/jbpm/console/ng/wi/backend/server/cases/service/CaseProjectServiceImpl.java
jbpm-console-ng-workbench-integration/jbpm-console-ng-workbench-integration-backend/src/main/resources/CaseWorkDefinitions.wid
jbpm-console-ng-workbench-integration/jbpm-console-ng-workbench-integration-backend/src/test/java/org/jbpm/console/ng/wi/backend/server/cases/service/CaseProjectServiceImplTest.java
jbpm-console-ng-workbench-integration/jbpm-console-ng-workbench-integration-client/pom.xml
jbpm-console-ng-workbench-integration/jbpm-console-ng-workbench-integration-client/src/main/java/org/jbpm/console/ng/wi/client/handlers/NewCaseProjectHandler.java
jbpm-console-ng-workbench-integration/jbpm-console-ng-workbench-integration-client/src/main/java/org/jbpm/console/ng/wi/client/i18n/Constants.java
jbpm-console-ng-workbench-integration/jbpm-console-ng-workbench-integration-client/src/main/resources/org/jbpm/console/ng/wi/client/i18n/Constants.properties

@cristianonicolai @nmirasch could you please have a look?

JBPM-5355 - Support case project

---

jbpm-console-ng-executor-service/jbpm-console-ng-executor-service-client/src/main/java/org/jbpm/console/ng/es/client/editors/quicknewjob/QuickNewJobPopup.java
jbpm-console-ng-executor-service/jbpm-console-ng-executor-service-client/src/test/java/org/jbpm/console/ng/es/client/editors/quicknewjob/QuickNewJobPopupTest.java

@cristianonicolai  can you review? thanks!

JBPM-5266: Jobs: Type validation fails during new job creation

---

jbpm-console-ng-executor-service/jbpm-console-ng-executor-service-client/src/main/java/org/jbpm/console/ng/es/client/editors/requestlist/RequestListPresenter.java
jbpm-console-ng-executor-service/jbpm-console-ng-executor-service-client/src/test/java/org/jbpm/console/ng/es/client/editors/requestlist/RequestListPresenterTest.java

Adding test coverage for filters conditions generation in Jobs perspective.
The added test methods and accompanying code re-factoring in the Presenter class are aligned with the approach taken for Process Instances and Tasks perspectives (e.g DataSetProcessInstanceWithVariablesListPresenter.java).

Add unit tests for Jobs perspective filter creation

---

jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-backend/src/main/java/org/jbpm/console/ng/cm/backend/server/CaseCommentsMapper.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-backend/src/main/java/org/jbpm/console/ng/cm/backend/server/CaseInstanceMapper.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-backend/src/main/java/org/jbpm/console/ng/cm/backend/server/RemoteCaseManagementServiceImpl.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-backend/src/main/java/org/jbpm/console/ng/cm/backend/server/RoleAssignmentsMapper.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-backend/src/test/java/org/jbpm/console/ng/cm/backend/server/RemoteCaseManagementServiceImplTest.java

* RemoteCaseManagementServiceImplTest - added test for case sorting, getCaseInstance and getCaseDefinition (for cases when remote client returns null), reused some string constants
* Exrtacted CaseCommentsMapper and  RoleAssignmentsMapper

Review & expand RemoteCaseManagementServiceImplTest

---

jbpm-console-ng-workbench-forms-integration/jbpm-console-ng-workbench-forms-integration-backend/src/test/java/org/jbpm/console/ng/workbench/forms/display/backend/provider/AbstractFormProvidingEngineTest.java

KIE forms jBPM integration:

---

jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-backend/src/main/java/org/jbpm/console/ng/cm/backend/server/CaseCommentMapper.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-backend/src/main/java/org/jbpm/console/ng/cm/backend/server/RemoteCaseManagementServiceImpl.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-backend/src/test/java/org/jbpm/console/ng/cm/backend/server/CaseCommentMapperTest.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-backend/src/test/java/org/jbpm/console/ng/cm/backend/server/CaseDefinitionMapperTest.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-backend/src/test/java/org/jbpm/console/ng/cm/backend/server/CaseInstanceMapperTest.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-backend/src/test/java/org/jbpm/console/ng/cm/backend/server/RemoteCaseManagementServiceImplTest.java

Added new tests for Mapper classes and RemoteCaseManagementServiceImpl class and performed small re-factoring to align all test implementations.

case-mgmt-backend: Add new/re-factor existing unit tests

---

jbpm-console-ng-business-domain/jbpm-console-ng-business-domain-api/src/main/java/org/jbpm/console/ng/bd/integration/ConsoleDataSetLookup.java
jbpm-console-ng-business-domain/jbpm-console-ng-business-domain-backend/src/main/java/org/jbpm/console/ng/bd/integration/KieServerDataSetProvider.java
jbpm-console-ng-business-domain/jbpm-console-ng-business-domain-backend/src/test/java/org/jbpm/console/ng/bd/integration/KieServerDataSetProviderTest.java
jbpm-console-ng-dashboard/jbpm-console-ng-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/AbstractDashboard.java
jbpm-console-ng-generic/jbpm-console-ng-data-filters-client/pom.xml
jbpm-console-ng-generic/jbpm-console-ng-data-filters-client/src/main/java/org/jbpm/console/ng/df/client/list/base/DataSetEditorManager.java
jbpm-console-ng-generic/jbpm-console-ng-data-filters-client/src/main/java/org/jbpm/console/ng/df/client/list/base/DataSetQueryHelper.java
jbpm-console-ng-generic/jbpm-console-ng-data-filters-client/src/main/resources/org/jbpm/console/ng/df/JbpmConsoleNGDataFiltersClient.gwt.xml
jbpm-console-ng-generic/jbpm-console-ng-generic-api/pom.xml

Removed unused dependencies
Removed unused code
Moved Kie Server related code to business-domain-api module

data-filters-client module dependencies review

---

jbpm-console-ng-generic/jbpm-console-ng-generic-forms/jbpm-console-ng-generic-forms-api/src/main/java/org/jbpm/console/ng/ga/forms/service/providing/DefaultFormProvider.java
jbpm-console-ng-generic/jbpm-console-ng-generic-forms/jbpm-console-ng-generic-forms-backend/pom.xml
jbpm-console-ng-generic/jbpm-console-ng-generic-forms/jbpm-console-ng-generic-forms-backend/src/main/java/org/jbpm/console/ng/ga/forms/display/backend/FormServiceEntryPointImpl.java
jbpm-console-ng-generic/jbpm-console-ng-generic-forms/jbpm-console-ng-generic-forms-backend/src/main/java/org/jbpm/console/ng/ga/forms/display/backend/provider/ClasspathFormProvider.java
jbpm-console-ng-generic/jbpm-console-ng-generic-forms/jbpm-console-ng-generic-forms-backend/src/main/java/org/jbpm/console/ng/ga/forms/display/backend/provider/FreemakerFormProvider.java
jbpm-console-ng-generic/jbpm-console-ng-generic-forms/jbpm-console-ng-generic-forms-backend/src/main/java/org/jbpm/console/ng/ga/forms/display/backend/provider/InMemoryFormProvider.java
jbpm-console-ng-generic/jbpm-console-ng-generic-forms/jbpm-console-ng-generic-forms-backend/src/test/java/org/jbpm/console/ng/ga/forms/display/backend/FormServiceEntryPointImplTest.java
jbpm-console-ng-generic/jbpm-console-ng-generic-forms/jbpm-console-ng-generic-forms-backend/src/test/resources/forms/form.ftl
jbpm-console-ng-human-tasks-forms/jbpm-console-ng-human-tasks-forms-client/src/main/java/org/jbpm/console/ng/ht/forms/client/display/providers/HumanTaskFormDisplayProviderImpl.java
jbpm-console-ng-human-tasks-forms/jbpm-console-ng-human-tasks-forms-client/src/main/java/org/jbpm/console/ng/ht/forms/client/i18n/Constants.java
jbpm-console-ng-human-tasks-forms/jbpm-console-ng-human-tasks-forms-client/src/main/resources/org/jbpm/console/ng/ht/forms/client/i18n/Constants.properties
jbpm-console-ng-process-runtime-forms/jbpm-console-ng-process-runtime-forms-client/src/main/java/org/jbpm/console/ng/pr/forms/client/display/providers/StartProcessFormDisplayProviderImpl.java
jbpm-console-ng-process-runtime-forms/jbpm-console-ng-process-runtime-forms-client/src/main/java/org/jbpm/console/ng/pr/forms/client/i18n/Constants.java
jbpm-console-ng-process-runtime-forms/jbpm-console-ng-process-runtime-forms-client/src/main/resources/org/jbpm/console/ng/pr/forms/client/i18n/Constants.properties

Fixing issue generating default forms when process / task doesn't have a defined form.

Fixing default form issues

---

jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-api/src/main/java/org/jbpm/console/ng/cm/service/CaseManagementService.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-backend/src/main/java/org/jbpm/console/ng/cm/backend/server/RemoteCaseManagementServiceImpl.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-backend/src/test/java/org/jbpm/console/ng/cm/backend/server/RemoteCaseManagementServiceImplTest.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/comments/CaseCommentsPresenter.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/test/java/org/jbpm/console/ng/cm/client/comments/CaseCommentsPresenterTest.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-showcase/src/main/java/org/jbpm/console/ng/cm/server/MockCaseManagementService.java

Review page size to -1 instead of Integer.MAX_VALUE

Fix case comments pagination limit

---

jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/util/AbstractCaseInstancePresenter.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/test/java/org/jbpm/console/ng/cm/client/comments/CaseCommentsPresenterTest.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/test/java/org/jbpm/console/ng/cm/client/overview/CaseOverviewPresenterTest.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/test/java/org/jbpm/console/ng/cm/client/roles/CaseRolesPresenterTest.java

@cristianonicolai Validation change we discussed. But when building jbpm-console-ng locally, i'm getting 1 reproducible fail in `CaseRolesPresenterTest.testLoadCaseInstance` but I have no idea how this is related to my change..

Fix AbstractCaseInstancePresenter place req.param validation

---

jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/list/CaseInstanceListViewImpl.html

Avoid page reload when first used.

Fix button for start case

---

jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-api/src/main/java/org/jbpm/console/ng/cm/model/CaseMilestoneSummary.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-api/src/main/java/org/jbpm/console/ng/cm/service/CaseManagementService.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-api/src/main/java/org/jbpm/console/ng/cm/util/CaseMilestoneSearchRequest.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-backend/src/main/java/org/jbpm/console/ng/cm/backend/server/CaseMilestoneMapper.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-backend/src/main/java/org/jbpm/console/ng/cm/backend/server/RemoteCaseManagementServiceImpl.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-backend/src/test/java/org/jbpm/console/ng/cm/backend/server/CaseMilestoneMapperTest.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-backend/src/test/java/org/jbpm/console/ng/cm/backend/server/RemoteCaseManagementServiceImplTest.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/list/CaseInstanceViewImpl.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/milestones/CaseMilestoneItemView.html
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/milestones/CaseMilestoneItemView.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/milestones/CaseMilestoneListPresenter.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/milestones/CaseMilestoneListSearchViewImpl.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/milestones/CaseMilestoneListViewImpl.html
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/milestones/CaseMilestoneListViewImpl.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/overview/CaseOverviewPresenter.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/overview/CaseOverviewViewImpl.html
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/overview/CaseOverviewViewImpl.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/resources/i18n/Constants.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/util/CaseMilestoneStatus.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/resources/org/jbpm/console/ng/cm/client/resources/i18n/Constants.properties
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/test/java/org/jbpm/console/ng/cm/client/milestones/CaseMilestonesPresenterTest.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-showcase/src/main/java/org/jbpm/console/ng/cm/server/MockCaseManagementService.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-showcase/src/main/resources/case_milestones.json

@cristianonicolai First approach for case milestones

JBPM-5214: Case Milestones

---

jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-backend/src/main/java/org/jbpm/console/ng/cm/backend/server/RemoteCaseManagementServiceImpl.java

Temporary fix to load max results until pagination is in place.

Fix pagination limit exception

---

jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/comments/CaseCommentsViewImpl.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/test/java/org/jbpm/console/ng/cm/client/comments/CaseCommentsPresenterTest.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/test/java/org/jbpm/console/ng/cm/client/util/AbstractCaseInstancePresenterTest.java

Added a couple of more tests for Case Comments and did a minor re-factoring around it.

case-mgmt-client: Case Comments - add unit tests

---

jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-api/src/main/java/org/jbpm/console/ng/cm/model/CaseInstanceSummary.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-api/src/main/java/org/jbpm/console/ng/cm/model/CaseStageSummary.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-backend/src/main/java/org/jbpm/console/ng/cm/backend/server/CaseInstanceMapper.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-backend/src/main/java/org/jbpm/console/ng/cm/backend/server/CaseStageMapper.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-backend/src/test/java/org/jbpm/console/ng/cm/backend/server/CaseInstanceMapperTest.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/overview/CaseOverviewPresenter.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/resources/i18n/Constants.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/stages/CaseStageItemViewImpl.css
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/stages/CaseStageItemViewImpl.html
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/stages/CaseStageItemViewImpl.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/stages/CaseStagesPresenter.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/stages/CaseStagesViewImpl.html
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/stages/CaseStagesViewImpl.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/util/CaseStageStatus.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/resources/org/jbpm/console/ng/cm/client/resources/i18n/Constants.properties
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/test/java/org/jbpm/console/ng/cm/client/stages/CaseStagesPresenterTest.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-showcase/src/main/java/org/jbpm/console/ng/cm/server/MockCaseManagementService.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-showcase/src/main/resources/case_stages.json

@cristianonicolai first approach of case stages.

JBPM-5247: Case Stages

---

jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/comments/CaseCommentItemView.html
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/comments/CaseCommentItemView.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/comments/CaseCommentsPresenter.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/comments/CaseCommentsViewImpl.html
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/comments/CaseCommentsViewImpl.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/events/CaseCommentEditEvent.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/milestones/CaseMilestoneItemView.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/resources/org/jbpm/console/ng/cm/client/resources/i18n/Constants.properties
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/test/java/org/jbpm/console/ng/cm/client/comments/CaseCommentsPresenterTest.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-showcase/src/main/java/org/jbpm/console/ng/cm/server/MockCaseManagementService.java

JBPM-5241: Case Comments

---

jbpm-console-ng-human-tasks-forms-modeler/jbpm-console-ng-human-tasks-forms-modeler-client/pom.xml
jbpm-console-ng-human-tasks-forms-modeler/jbpm-console-ng-human-tasks-forms-modeler-client/src/main/java/org/jbpm/console/ng/ht/forms/modeler/client/editors/taskform/displayers/FormModellerStartProcessDisplayerImpl.java
jbpm-console-ng-human-tasks-forms-modeler/jbpm-console-ng-human-tasks-forms-modeler-client/src/main/java/org/jbpm/console/ng/ht/forms/modeler/client/editors/taskform/displayers/FormModellerTaskDisplayerImpl.java
jbpm-console-ng-human-tasks-forms-modeler/jbpm-console-ng-human-tasks-forms-modeler-client/src/test/java/org/jbpm/console/ng/ht/forms/modeler/client/editors/taskform/displayers/FormModellerStartProcessDisplayerTest.java
jbpm-console-ng-human-tasks-forms-modeler/jbpm-console-ng-human-tasks-forms-modeler-client/src/test/java/org/jbpm/console/ng/ht/forms/modeler/client/editors/taskform/displayers/FormModellerTaskDisplayerTest.java
jbpm-console-ng-human-tasks-forms-modeler/jbpm-console-ng-human-tasks-forms-modeler-client/src/test/java/org/jbpm/console/ng/ht/forms/modeler/client/editors/taskform/displayers/test/TestFormModellerStartProcessDisplayerImpl.java
jbpm-console-ng-human-tasks-forms-modeler/jbpm-console-ng-human-tasks-forms-modeler-client/src/test/java/org/jbpm/console/ng/ht/forms/modeler/client/editors/taskform/displayers/test/TestFormModellerTaskDisplayerImpl.java
jbpm-console-ng-human-tasks-forms/jbpm-console-ng-human-tasks-forms-client/src/main/java/org/jbpm/console/ng/ht/forms/client/display/displayers/task/AbstractHumanTaskFormDisplayer.java
jbpm-console-ng-process-runtime-forms/jbpm-console-ng-process-runtime-forms-client/src/main/java/org/jbpm/console/ng/pr/forms/client/display/displayers/process/AbstractStartProcessFormDisplayer.java
jbpm-console-ng-workbench-integration/jbpm-console-ng-workbench-integration-client/src/main/java/org/jbpm/console/ng/wi/client/handlers/NewCaseProjectHandler.java

- Fixed CDI related errors when displaying old jbpm-form-modeler forms
- API changes on resource cration on Workbench
Comment: merge with https://github.com/droolsjbpm/kie-wb-common/pull/585

KIE forms jBPM integration

---

jbpm-console-ng-human-tasks-forms-modeler/jbpm-console-ng-human-tasks-forms-modeler-client/pom.xml
jbpm-console-ng-human-tasks-forms-modeler/jbpm-console-ng-human-tasks-forms-modeler-client/src/main/java/org/jbpm/console/ng/ht/forms/modeler/client/editors/taskform/displayers/FormModellerStartProcessDisplayerImpl.java
jbpm-console-ng-human-tasks-forms-modeler/jbpm-console-ng-human-tasks-forms-modeler-client/src/main/java/org/jbpm/console/ng/ht/forms/modeler/client/editors/taskform/displayers/FormModellerTaskDisplayerImpl.java
jbpm-console-ng-human-tasks-forms-modeler/jbpm-console-ng-human-tasks-forms-modeler-client/src/test/java/org/jbpm/console/ng/ht/forms/modeler/client/editors/taskform/displayers/FormModellerStartProcessDisplayerTest.java
jbpm-console-ng-human-tasks-forms-modeler/jbpm-console-ng-human-tasks-forms-modeler-client/src/test/java/org/jbpm/console/ng/ht/forms/modeler/client/editors/taskform/displayers/FormModellerTaskDisplayerTest.java
jbpm-console-ng-human-tasks-forms-modeler/jbpm-console-ng-human-tasks-forms-modeler-client/src/test/java/org/jbpm/console/ng/ht/forms/modeler/client/editors/taskform/displayers/test/TestFormModellerStartProcessDisplayerImpl.java
jbpm-console-ng-human-tasks-forms-modeler/jbpm-console-ng-human-tasks-forms-modeler-client/src/test/java/org/jbpm/console/ng/ht/forms/modeler/client/editors/taskform/displayers/test/TestFormModellerTaskDisplayerImpl.java
jbpm-console-ng-human-tasks-forms/jbpm-console-ng-human-tasks-forms-client/src/main/java/org/jbpm/console/ng/ht/forms/client/display/displayers/task/AbstractHumanTaskFormDisplayer.java
jbpm-console-ng-process-runtime-forms/jbpm-console-ng-process-runtime-forms-client/src/main/java/org/jbpm/console/ng/pr/forms/client/display/displayers/process/AbstractStartProcessFormDisplayer.java

Fixing NPE rendering jbpm-form-modeler forms.

Fixing NPE rendering jbpm-form-modeler forms.

---

jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/pom.xml
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/test/java/org/jbpm/console/ng/cm/client/roles/CaseRolesPresenterTest.java
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/test/java/org/jbpm/console/ng/cm/client/util/AbstractCaseInstancePresenterTest.java

Commit consists of: 
1. Re-factored existing Case Roles tests, mainly around test data initialization (so that parent test class is used more and common data shared among tests) and more efficient verification in some tests.
2. New tests aiming to cover in more details code branching at certain places in Presenter class

Case Roles: Re-factor existing and add new tests

---

jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-showcase/pom.xml
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-showcase/src/main/java/org/jbpm/console/ng/cm/server/DemoExamplesProvisioningService.java
jbpm-console-ng-kie-server/jbpm-console-ng-kie-server-api/src/main/java/org/jbpm/console/ng/ks/utils/KieServerUtils.java
jbpm-console-ng-kie-server/jbpm-console-ng-kie-server-backend/src/main/java/org/jbpm/console/ng/ks/integration/KieServerIntegration.java

Use Guvnor ALA API to provision demo projects into currently connected Kie Server.

Provision Case Management examples into Kie Server

---

jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-showcase/README.md
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-showcase/pom.xml
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-showcase/src/main/docker/settings.xml
jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-showcase/src/main/docker/standalone-full-jbpm.xml

New docker image that integrates the showcase app with a running Kie Server.
Provides default user and provisioning of example containers.
Builds on a separated profile to avoid issues with systems without Docker installed.

Build docker image for Case Management showcase integration demo

---

jbpm-console-ng-forms/.gitignore
jbpm-console-ng-generic/jbpm-console-ng-generic-client/src/main/java/org/jbpm/console/ng/gc/client/perspectives/ExperimentalPagingPerspective.html
jbpm-console-ng-generic/jbpm-console-ng-generic-client/src/main/java/org/jbpm/console/ng/gc/client/perspectives/ExperimentalPagingPerspective.java

Depends on https://github.com/uberfire/uberfire/pull/581

[UF-448] Upgrade Templated Perspectives to Errai UI

---

jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-showcase/pom.xml
jbpm-console-ng-dashboard/jbpm-console-ng-dashboard-backend/src/test/resources/META-INF/persistence.xml
jbpm-console-ng-forms/jbpm-console-ng-human-tasks-forms-modeler/jbpm-console-ng-human-tasks-forms-modeler-backend/pom.xml
jbpm-console-ng-forms/jbpm-console-ng-human-tasks-forms/jbpm-console-ng-human-tasks-forms-backend/pom.xml
jbpm-console-ng-forms/jbpm-console-ng-process-runtime-forms/jbpm-console-ng-process-runtime-forms-backend/pom.xml
jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-backend/src/test/resources/META-INF/persistence.xml
jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-backend/src/test/resources/META-INF/persistence.xml

Please don't merge yet. All the IP BOM 7.0.0.CR5 PRs need to be merged together.

Fixes after JPA 2.0 to 2.1 upgrade

---

jbpm-console-ng-executor-service/jbpm-console-ng-executor-service-client/src/main/java/org/jbpm/console/ng/es/client/editors/requestlist/RequestListPresenter.java
jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskslist/grid/AbstractTasksListGridPresenter.java
jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/test/java/org/jbpm/console/ng/ht/client/editors/taskslist/grid/AbstractTasksListGridPresenterTest.java
jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/main/java/org/jbpm/console/ng/pr/client/editors/instance/list/variables/dash/DataSetProcessInstanceVariableListPresenter.java
jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/main/java/org/jbpm/console/ng/pr/client/editors/instance/list/variables/dash/DataSetProcessInstanceWithVariablesListPresenter.java
jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/test/java/org/jbpm/console/ng/pr/client/editors/instance/list/variables/dash/DataSetProcessInstanceWithVariablesListPresenterTest.java

Added a check before the data is loaded in table rows to verify that the results match with the last tab  requested to avoid fill data with previous request.

JBPM-4246: Jobs: Queued tab displays jobs in status DONE

---

jbpm-console-ng-showcase/pom.xml

Preference API changed, so I needed to make some minor changes here.
Dependes on: https://github.com/uberfire/uberfire/pull/605

UF-459: Preference API Refactor

---

jbpm-wb-forms/jbpm-wb-forms-backend/pom.xml
jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/TaskFormValuesProcessor.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormProvidingEngineTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/resources/forms/Client.frm
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/resources/forms/Invoice.frm
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/resources/forms/InvoiceLine.frm
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/resources/forms/invoices-taskform.frm
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/resources/forms/modify-taskform.frm
jbpm-wb-showcase/pom.xml

- added dependencies to the missing forms ADF engine
- refactored changed API's
- fixed testing issues
These PR's should be merged together:
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/364
https://github.com/droolsjbpm/kie-wb-common/pull/640
https://github.com/droolsjbpm/jbpm-console-ng/pull/609
https://github.com/droolsjbpm/jbpm-designer/pull/533
https://github.com/droolsjbpm/appformer/pull/66
https://github.com/droolsjbpm/kie-wb-distributions/pull/446

JBPM-5573: Stunner - Integration of latest KIE Forms API & implementations

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/README.md
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/src/main/webapp/WEB-INF/beans.xml
jbpm-wb-showcase/src/main/webapp/WEB-INF/beans.xml

Removed outdated packages from beans.xml
Update case-mgmt docs

 JBPM-5530 - Remove references to console-ng

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-api/src/main/java/org/jbpm/workbench/cm/service/CaseManagementService.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/src/main/java/org/jbpm/workbench/cm/backend/server/RemoteCaseManagementServiceImpl.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/src/test/java/org/jbpm/workbench/cm/backend/server/RemoteCaseManagementServiceImplTest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/newcase/NewCaseInstancePresenter.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/newcase/NewCaseInstanceViewImpl.html
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/newcase/NewCaseInstanceViewImpl.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/resources/i18n/Constants.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/resources/org/jbpm/workbench/cm/client/resources/i18n/Constants.properties
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/newcase/NewCaseInstancePresenterTest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/src/main/java/org/jbpm/workbench/cm/server/MockCaseManagementService.java

By default, current user is set as owner

JBPM-5410 - Allow providing case owner to start a case instance

---

jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/perspectives/JobListPerspective.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskprocesscontext/TaskProcessContextPresenter.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/perspectives/DataSetTasksListPerspective.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/perspectives/DataSetProcessInstancesWithVariablesPerspective.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/perspectives/ProcessDefinitionsPerspective.java
jbpm-wb-showcase/src/main/java/org/jbpm/workbench/client/ShowcaseEntryPoint.java
jbpm-wb-showcase/src/main/java/org/jbpm/workbench/client/screens/HomeViewImpl.java

@cristianonicolai  can you take a look?

JBPM perspectives id renaming

---

jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/DeploymentDescriptorEditorPresenter.java

* ValidationPopup refactoring
Part of:
https://github.com/droolsjbpm/guvnor/pull/416
https://github.com/droolsjbpm/jbpm-wb/pull/630
https://github.com/droolsjbpm/kie-wb-common/pull/681
https://github.com/droolsjbpm/optaplanner-wb/pull/134

PLANNER-736: Workbench: Prevent user from creating multiple @PlanningSolution data objects

---

jbpm-console-ng-generic/jbpm-console-ng-generic-forms-api/src/main/java/org/jbpm/console/ng/ga/forms/display/view/FormDisplayerView.java
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-client/pom.xml
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-client/src/main/java/org/jbpm/console/ng/gc/forms/client/display/views/GenericFormDisplayView.java
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-client/src/main/java/org/jbpm/console/ng/gc/forms/client/display/views/display/EmbeddedFormDisplayer.java
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-client/src/main/java/org/jbpm/console/ng/gc/forms/client/display/views/display/EmbeddedFormDisplayerView.java
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-client/src/main/java/org/jbpm/console/ng/gc/forms/client/display/views/display/EmbeddedFormDisplayerViewImpl.css
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-client/src/main/java/org/jbpm/console/ng/gc/forms/client/display/views/display/EmbeddedFormDisplayerViewImpl.html
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-client/src/main/java/org/jbpm/console/ng/gc/forms/client/display/views/display/EmbeddedFormDisplayerViewImpl.java
jbpm-console-ng-generic/jbpm-console-ng-generic-forms-client/src/test/java/org/jbpm/console/ng/gc/forms/client/display/views/display/EmbeddedFormDisplayerTest.java
jbpm-console-ng-human-tasks-forms/jbpm-console-ng-human-tasks-forms-api/src/main/java/org/jbpm/console/ng/ht/forms/display/ht/api/TaskFormPermissionDeniedException.java
jbpm-console-ng-human-tasks-forms/jbpm-console-ng-human-tasks-forms-backend/src/main/java/org/jbpm/console/ng/ht/forms/backend/server/FormServiceEntryPointImpl.java
jbpm-console-ng-human-tasks-forms/jbpm-console-ng-human-tasks-forms-client/src/main/java/org/jbpm/console/ng/ht/forms/client/display/providers/HumanTaskFormDisplayProviderImpl.java
jbpm-console-ng-human-tasks-forms/jbpm-console-ng-human-tasks-forms-client/src/main/java/org/jbpm/console/ng/ht/forms/client/display/standalone/StandaloneTaskFormDisplayPresenter.java
jbpm-console-ng-human-tasks-forms/jbpm-console-ng-human-tasks-forms-client/src/main/java/org/jbpm/console/ng/ht/forms/client/i18n/Constants.java
jbpm-console-ng-human-tasks-forms/jbpm-console-ng-human-tasks-forms-client/src/main/resources/org/jbpm/console/ng/ht/forms/client/i18n/Constants.properties
jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskform/TaskFormViewImpl.java
jbpm-console-ng-process-runtime-forms/jbpm-console-ng-process-runtime-forms-client/src/main/java/org/jbpm/console/ng/pr/forms/client/display/standalone/StandaloneProcessFormDisplayScreen.java
jbpm-console-ng-process-runtime-forms/jbpm-console-ng-process-runtime-forms-client/src/main/java/org/jbpm/console/ng/pr/forms/client/display/views/PopupFormDisplayerView.java
jbpm-console-ng-process-runtime-forms/jbpm-console-ng-process-runtime-forms-client/src/main/java/org/jbpm/console/ng/pr/forms/client/editors/quicknewinstance/QuickNewProcessInstancePopup.java

@cristianonicolai can you take a look?
This PR should be merged with:
- https://github.com/droolsjbpm/jbpm/pull/756
- https://github.com/droolsjbpm/droolsjbpm-integration/pull/828

RHBPMS-4576: A user can display tasks for which he is not Potential Owner or Bussines Admin

---

jbpm-wb-integration/jbpm-wb-integration-api/src/main/java/org/jbpm/workbench/wi/casemgmt/service/CaseProvisioningSettings.java
jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseProvisioningServiceImpl.java
jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseProvisioningSettingsImpl.java

Removed unused Wildfly port system property
Renamed host to management host to better describe its use.

Provisioning API enhancements

---

jbpm-wb-integration/jbpm-wb-integration-api/src/main/java/org/jbpm/workbench/wi/casemgmt/service/CaseProvisioningSettings.java
jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseProvisioningServiceImpl.java
jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseProvisioningSettingsImpl.java
jbpm-wb-integration/jbpm-wb-integration-client/pom.xml
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/casemgmt/CaseProvisioningAppLauncherHandler.java
jbpm-wb-integration/jbpm-wb-integration-client/src/test/java/org/jbpm/workbench/wi/client/casemgmt/CaseProvisioningAppLauncherHandlerTest.java

Added new system property org.jbpm.casemgmt.showcase.url to allow specifying the context/url where the case management showcase app is deployed.

JBPM-5800 - Included showcase app link if war is manually deployed

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-api/src/main/java/org/jbpm/workbench/cm/util/KieServerException.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/pom.xml
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/src/main/java/org/jbpm/workbench/cm/backend/server/KieServerExceptionHandler.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/src/main/java/org/jbpm/workbench/cm/backend/server/KieServerExceptionInterceptor.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/src/main/java/org/jbpm/workbench/cm/backend/server/RemoteCaseManagementServiceImpl.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/src/main/resources/META-INF/beans.xml
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/src/test/java/org/jbpm/workbench/cm/backend/server/KieServerExceptionInterceptorTest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/newcase/NewCaseInstancePresenter.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/newcase/NewCaseInstanceViewImpl.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/resources/i18n/Constants.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/util/ErrorPopup.html
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/util/ErrorPopup.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/util/InlineNotification.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/resources/org/jbpm/workbench/cm/client/resources/i18n/Constants.properties
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/src/main/java/org/jbpm/workbench/cm/client/ShowcaseEntryPoint.java

Add error callback for handling errors at case start popup
New generic error popup for unhandled exceptions
New exception interceptor to transform Kie Server exceptions

JBPM-5816 - Improve general exception handling

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/actions/CaseActionsListViewImpl.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/actions/CaseActionsViewImpl.html
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/comments/CaseCommentItemView.html
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/comments/CaseCommentItemView.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/comments/CaseCommentsViewImpl.html
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/comments/CaseCommentsViewImpl.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/details/CaseDetailsViewImpl.html
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/milestones/CaseMilestoneListViewImpl.html
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/overview/CaseOverviewViewImpl.html
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/roles/CaseRolesViewImpl.html
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/roles/CaseRolesViewImpl.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/stages/CaseStagesViewImpl.html
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/resources/org/jbpm/workbench/cm/static/case-mgmt.less
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/resources/org/jbpm/workbench/cm/static/kie-nav-wizard.less
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/resources/org/jbpm/workbench/cm/static/kie-variables.less
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/src/main/resources/case_definitions.json

Updated the css styles with the latest ones
Added scroll in milestone to ensure the fixed height
Added a min-height restriction over the displayed cards
Changed the page_size of actions and roles to fit with the design provided by UX

JBPM-5770: Use fixed height for blocks/cards

---

jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/tasklogs/TaskLogsPresenter.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/tasklogs/TaskLogsViewImpl.html
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/tasklogs/TaskLogsViewImpl.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/resources/i18n/Constants.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/resources/org/jbpm/workbench/ht/client/resources/i18n/Constants.properties
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/test/java/org/jbpm/workbench/ht/client/editors/tasklogs/TaskLogsPresenterTest.java

Use list to handle items instead of building the html manually
Remove label string
Fix and reformat test code

Review task logs panel details

---

jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/definition/details/multi/BaseProcessDefDetailsMultiPresenter.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListPresenter.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListViewImpl.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/perspectives/ProcessInstanceListPerspective.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/definition/details/multi/BaseProcessDefDetailsMultiPresenterTest.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListPresenterTest.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListViewExtension.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListViewTest.java

Drop DataSet from classes name and remove unnecessary package names.

Process Instance List file naming review

---

jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskprocesscontext/TaskProcessContextPresenter.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/test/java/org/jbpm/workbench/ht/client/editors/taskprocesscontext/TaskProcessContextPresenterTest.java

Changed the process instances perspective id linked at  Process instance details button (Task details - Process context tab )

JBPM-5882: Link to process instances form Task details doesn't work

---

jbpm-wb-dashboard/jbpm-wb-dashboard-client/pom.xml
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/DashboardPerspective.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/pom.xml
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/perspectives/JobListPerspective.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/perspectives/DataSetTasksListPerspective.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/definition/details/multi/BaseProcessDefDetailsMultiPresenter.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/perspectives/ProcessDefinitionsPerspective.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/perspectives/ProcessInstanceListPerspective.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/definition/details/multi/BaseProcessDefDetailsMultiPresenterTest.java

Avoid duplication and mismatch

Reuse shared PerspectiveIds

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/src/main/java/org/jbpm/workbench/cm/backend/server/RemoteCaseManagementServiceImpl.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/src/test/java/org/jbpm/workbench/cm/backend/server/RemoteCaseManagementServiceImplTest.java

Added the getCompletedNodes service call

JBPM-5246: Case Actions - Completed

---

jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormProvidingEngineTest.java

This PR adapts the testing to a code change introduced in https://github.com/kiegroup/kie-wb-common/pull/771
@nmirasch @cristianonicolai can you take a look?
Comment merge with:
https://github.com/kiegroup/kie-wb-common/pull/771
https://github.com/kiegroup/jbpm-designer/pull/564

JBPM-5738: Add default configuration for fields that nest forms.

---

jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/menu/ServerTemplateSelectorMenuBuilder.java
jbpm-wb-common/jbpm-wb-common-client/src/test/java/org/jbpm/workbench/common/client/menu/ServerTemplateSelectorMenuBuilderTest.java

Cherry pick change #692  into 7.0.x branch

JBPM-5695: Exception in Task list for restarted Kie server (#692)

---

jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/main/java/org/jbpm/workbench/pr/backend/server/DataSetDefsBootstrap.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListViewImpl.java

Unified last modification date or process instance end date at SQL level.

BPMSPL-632 & JBPM-5918: fixed sorting on last update column

---

jbpm-wb-dashboard/jbpm-wb-dashboard-backend/src/test/resources/META-INF/persistence.xml
jbpm-wb-human-tasks/jbpm-wb-human-tasks-backend/src/test/resources/META-INF/persistence.xml
jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/test/resources/META-INF/persistence.xml

Add ExecutionErrorInfo class to JPA persistence unit

Fix database tests

---

jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/DashboardKpis.java
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/ProcessDashboard.java
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/TaskDashboard.java
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/test/java/org/jbpm/dashboard/renderer/client/ProcessDashboardTest.java
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/test/java/org/jbpm/dashboard/renderer/client/TaskDashboardTest.java

Fix + tests.
NOTE: It is a regression caused by https://issues.jboss.org/browse/JBPM-4851
@romartin Can you review & approve please?
Depends on dashbuilder/dashbuilder#317

JBPM-5834: Metric displayers in process & task dashboards are broken (0.7.x)

---

jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/DashboardKpis.java
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/ProcessDashboard.java
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/TaskDashboard.java
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/test/java/org/jbpm/dashboard/renderer/client/ProcessDashboardTest.java
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/test/java/org/jbpm/dashboard/renderer/client/TaskDashboardTest.java

Fix + tests.
NOTE: It is a regression caused by https://issues.jboss.org/browse/JBPM-4851 
@romartin Can you review & approve please?
Depends on https://github.com/dashbuilder/dashbuilder/pull/316

JBPM-5834: Metric displayers in process & task dashboards are broken

---

jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/AbstractTaskListPresenter.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/AbstractTaskListView.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/TaskAdminListPresenter.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/TaskAdminListViewImpl.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/TaskListViewImpl.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/perspectives/TaskAdminListPerspective.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/resources/i18n/Constants.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/resources/org/jbpm/workbench/ht/client/resources/i18n/Constants.properties
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/test/java/org/jbpm/workbench/ht/client/editors/taskslist/AbstractTaskListPresenterTest.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/test/java/org/jbpm/workbench/ht/client/editors/taskslist/AbstractTaskListViewTest.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/test/java/org/jbpm/workbench/ht/client/editors/taskslist/TaskAdminListPresenterTest.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/test/java/org/jbpm/workbench/ht/client/editors/taskslist/TaskAdminListViewImplTest.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/test/java/org/jbpm/workbench/ht/client/editors/taskslist/TaskListPresenterTest.java
jbpm-wb-showcase/src/main/java/org/jbpm/workbench/client/ShowcaseEntryPoint.java
jbpm-wb-showcase/src/main/java/org/jbpm/workbench/client/i18n/Constants.java
jbpm-wb-showcase/src/main/resources/org/jbpm/workbench/client/i18n/Constants.properties

This PR depends on https://github.com/kiegroup/kie-wb-distributions/pull/494

BPMSPL-653: Separated task administration to new view

---

jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/util/TaskUtils.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/AbstractTaskListView.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/TaskListViewImpl.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/test/java/org/jbpm/workbench/ht/client/editors/taskslist/AbstractTaskListViewTest.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/test/java/org/jbpm/workbench/ht/client/editors/taskslist/TaskListViewImplTest.java

Separated suspend/resume conditions for admin task list and user task list.
Separated corresponding tests.

JBPM-6003: Task admin can't suspend/resume other users' tasks

---

jbpm-wb-executor-service/jbpm-wb-executor-service-api/src/main/java/org/jbpm/workbench/es/util/RequestStatus.java
jbpm-wb-executor-service/jbpm-wb-executor-service-api/src/main/resources/org/jbpm/workbench/es/JbpmWorkbenchExecutorServiceAPI.gwt.xml
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListViewImpl.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListViewImplTest.java

Add enum for status instead of Strings
Renamed test class to mach impl

Updates to RequestListViewImpl

---

jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListViewImpl.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListViewImplTest.java

Removed unused code
Use GWT.create to initialize widgets so GWTMockito can properly mock classes for test
Renamed test class to mach impl

Updates to ProcessInstanceListViewImpl

---

jbpm-wb-forms/jbpm-wb-forms-client/pom.xml
jbpm-wb-forms/jbpm-wb-forms-client/src/main/java/org/jbpm/workbench/forms/client/GenericFormsClientEntryPoint.java
jbpm-wb-forms/jbpm-wb-forms-client/src/main/resources/org/jbpm/workbench/forms/JbpmWorkbenchFormsClient.gwt.xml

See https://issues.jboss.org/browse/UF-517

UF-517: Bootstrap Selector CSS overriding Patternfly Selector CSS

---

jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListViewImpl.java

This PR depends on https://github.com/kiegroup/kie-wb-common/pull/906

BPMSPL-633: Added basic navigation to errors view

---

jbpm-wb-showcase/pom.xml

depends on AppFormer/uberfire#740

AF-527: aded new appformer maven support artifact for gwt build

---

jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/TaskFormValuesProcessor.java

JBPM-5926: Improve form reusability when different tasks use the same form.
JBPM-5977: Incorrect task form-model is generated for a task in a subprocess.
@cristianonicolai @jsoltes could you take a look please?
Comment: merge with: https://github.com/kiegroup/kie-wb-common/pull/915

JBPM-5926 & JBPM-5977: Fixing form generation for Business Processes

---

jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/DeploymentDescriptorEditorPresenter.java

See https://issues.jboss.org/browse/JBPM-6069

JBPM-6069: Missing CRUD buttons in asset editors

---

jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/PerspectiveIds.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/errorlist/ExecutionErrorListPresenter.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/errorlist/ExecutionErrorListViewImpl.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListPresenter.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/i18n/Constants.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/resources/org/jbpm/workbench/es/client/i18n/Constants.properties
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/errorlist/ExecutionErrorListPresenterTest.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListPresenterTest.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListPresenter.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListPresenterTest.java

Add links to job view and Process Instances view form Execution errors list

JBPM-6079: Execution error goToJob and goToProcessInstance actions

---

jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/list/AdvancedSearchFiltersViewImpl.css
jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/list/AdvancedSearchFiltersViewImpl.html
jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/list/AdvancedSearchFiltersViewImpl.java

Add spacing between dropdowns
Move Date pickers to its own grouping

JBPM-5990 - UI improvements to quick search

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/CaseManagementEntryPoint.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/src/main/java/org/jbpm/workbench/cm/client/navbar/AppNavBar.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/src/main/java/org/jbpm/workbench/cm/client/navbar/LogoNavBar.java
jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/CommonEntryPoint.java
jbpm-wb-forms/jbpm-wb-forms-client/src/main/java/org/jbpm/workbench/forms/client/GenericFormsClientEntryPoint.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/IntegrationEntryPoint.java
jbpm-wb-showcase/src/main/java/org/jbpm/workbench/client/ShowcaseEntryPoint.java
jbpm-wb-showcase/src/main/java/org/jbpm/workbench/client/navbar/AppNavBar.java
jbpm-wb-showcase/src/test/java/org/jbpm/workbench/client/ShowcaseEntryPointTest.java

* Replace @AfterInitialization methods with @PostConstruct
* Remove PlaceManagerActivityService

AF-546: Reduce startup time of AppFormer apps and workbenches

---

jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/test/java/org/jbpm/dashboard/renderer/client/AbstractDashboardTest.java

Fix failing tests caused by the changes introduced the GWT displayers initialization => https://issues.jboss.org/browse/DASHBUILDE-230  
@cristianonicolai @nmirasch Can you review it please?

DASHBUILDE-230: PatternFly styling in filter selection labels

---

jbpm-wb-integration/jbpm-wb-integration-backend/src/main/resources/CaseWorkDefinitions.wid

just removing imports as no longer needed

JBPM-6144 - Create a wid specific MVELEvaluator

---

jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListPresenter.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListViewImpl.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListPresenterTest.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListViewImplTest.java

Refactor job actions using new ConditionalButtonActionCell class.
Moved conditions to show action buttons to Presenter.
Improved tests ( see https://github.com/kiegroup/jbpm-wb/pull/755#discussion_r121988544 )

Refactor job actions using new ConditionalButtonActionCell

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/src/main/resources/org/jbpm/workbench/cm/jBPMCaseManagement.gwt.xml
jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseProvisioningExecutor.java
jbpm-wb-integration/jbpm-wb-integration-backend/src/test/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseProvisioningServiceImplTest.java
jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/java/org/jbpm/workbench/ks/integration/KieServerDataSetManager.java
jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/test/java/org/jbpm/workbench/ks/integration/KieServerDataSetManagerTest.java

In this PR there are only some changes about the AsynExecutorServer that was deprecated and replace with ManagedExecutorService. It also include PreferenceAPI dependencies. This not affect the current behaviour.
Injection changed to constructor type.
Code formatted.

UF-506: Workspace Mechanism

---

jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/util/DataSetUtils.java
jbpm-wb-executor-service/jbpm-wb-executor-service-api/src/main/java/org/jbpm/workbench/es/model/ExecutionErrorSummary.java
jbpm-wb-executor-service/jbpm-wb-executor-service-backend/src/main/java/org/jbpm/workbench/es/backend/server/DataSetDefsBootstrap.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/errorlist/ExecutionErrorListPresenter.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/errordetails/ExecutionErrorDetailsPresenterTest.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/errorlist/ExecutionErrorListPresenterTest.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/main/java/org/jbpm/workbench/pr/backend/server/DataSetDefsBootstrap.java

Depends on https://github.com/kiegroup/jbpm/pull/893 which depends on https://github.com/kiegroup/droolsjbpm-knowledge/pull/242

JBPM-6121: Change error ack column type to number

---

jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceSummaryErrorPopoverCell.html
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceSummaryErrorPopoverCell.java

Improves UX of process instance error count popover by managing visibility manually

BPMSPL-633: Improved UX of error count popover

---

jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/AbstractTaskListView.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/resources/css/HumanTaskCSS.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/resources/org/jbpm/workbench/ht/client/resources/css/human-tasks.css
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/test/java/org/jbpm/workbench/ht/client/editors/taskslist/AbstractTaskListViewTest.java

Removed styling applied to Tasks list rows related with the task priority

JBPM-5436: workbench Tasks List priority colors are inconsistent

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/src/main/java/org/jbpm/workbench/cm/server/JGitFileSystemProvider.java
jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseProvisioningExecutor.java
jbpm-wb-integration/jbpm-wb-integration-backend/src/test/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseProvisioningServiceImplTest.java
jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/java/org/jbpm/workbench/ks/integration/KieServerDataSetManager.java
jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/test/java/org/jbpm/workbench/ks/integration/KieServerDataSetManagerTest.java

description: https://github.com/AppFormer/uberfire/pull/761

AF-559: replaced mangedexecutorservice with ExecutorService

---

jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/list/ActiveFilterItemView.java
jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/list/AdvancedSearchFiltersViewImpl.java
jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/list/DatePickerRange.java
jbpm-wb-common/jbpm-wb-common-client/src/test/java/org/jbpm/workbench/common/client/list/AdvancedSearchFiltersViewImplTest.java
jbpm-wb-common/jbpm-wb-data-filters-client/src/main/java/org/jbpm/workbench/df/client/list/DataSetEditorManager.java

Move date ranges to its own enum
Use JsInterop for popover and fix container property to properly show arrow

JBPM-6176 - Date range picker to use current time when adding new filter

---

jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceSummaryErrorPopoverCell.html
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceSummaryErrorPopoverCell.java

Fix error count popover selectors to avoid conflict with advanced search
filters

BPMSPL-633: Fix error count popover selectors

---

jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseProvisioningServiceImpl.java

Add missing provider-name parameter for ALA API

Fix Case Management Showcase app provisioning error

---

jbpm-wb-integration/jbpm-wb-integration-backend/pom.xml

GUVNOR-3023: Support provisioning of KIE Server instances by Guvnor ALA
https://issues.jboss.org/browse/GUVNOR-3023

GUVNOR-3023: Support provisioning of KIE Server instances by Guvnor ALA

---

jbpm-wb-showcase/pom.xml
jbpm-wb-showcase/src/main/resources/org/jbpm/workbench/jBPMShowcase.gwt.xml

This changes are introduced by: kiegroup/kie-wb-common#1009
@cristianonicolai  @jsoltes  could you review?
This PR is part of an ensemble, please merge with:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/490
https://github.com/kiegroup/kie-wb-common/pull/1009
https://github.com/kiegroup/drools-wb/pull/561
https://github.com/kiegroup/optaplanner-wb/pull/192
https://github.com/kiegroup/kie-wb-distributions/pull/563
https://github.com/kiegroup/jbpm-wb/pull/817
https://github.com/kiegroup/jbpm-form-modeler/pull/128

[7.2.x] JBPM-5531: Problems after deleting a form that is used as a subform in other form.

---

jbpm-wb-showcase/pom.xml
jbpm-wb-showcase/src/main/resources/org/jbpm/workbench/jBPMShowcase.gwt.xml

Copy of https://github.com/kiegroup/jbpm-wb/pull/817
@cristianonicolai @jsoltes could you review?
This PR is part of an ensemble, please merge with:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/508
https://github.com/kiegroup/kie-wb-common/pull/1069
https://github.com/kiegroup/drools-wb/pull/576
https://github.com/kiegroup/optaplanner-wb/pull/201
https://github.com/kiegroup/jbpm-wb/pull/844
https://github.com/kiegroup/kie-wb-distributions/pull/581
https://github.com/kiegroup/jbpm-form-modeler/pull/132

[7.3.x] JBPM-5531: Problems after deleting a form that is used as a subform in other form.

---

jbpm-wb-showcase/pom.xml

[7.3.x] JBPM-6310 - update to jbpm-workitems module (#845)

---

jbpm-wb-showcase/pom.xml
jbpm-wb-showcase/src/main/resources/org/jbpm/workbench/jBPMShowcase.gwt.xml

Copy of https://github.com/kiegroup/jbpm-wb/pull/817
@cristianonicolai @jsoltes could you review?
This PR is part of an ensemble, please merge with:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/493
https://github.com/kiegroup/kie-wb-common/pull/1011
https://github.com/kiegroup/drools-wb/pull/564
https://github.com/kiegroup/optaplanner-wb/pull/193
https://github.com/kiegroup/jbpm-wb/pull/819
https://github.com/kiegroup/kie-wb-distributions/pull/565
https://github.com/kiegroup/jbpm-form-modeler/pull/126

[8.0.x] JBPM-5531: Problems after deleting a form that is used as a subform in other form.

---

jbpm-wb-executor-service/jbpm-wb-executor-service-api/src/main/java/org/jbpm/workbench/es/model/RequestDataSetConstants.java
jbpm-wb-executor-service/jbpm-wb-executor-service-api/src/main/java/org/jbpm/workbench/es/model/RequestSummary.java
jbpm-wb-executor-service/jbpm-wb-executor-service-api/src/main/java/org/jbpm/workbench/es/service/ExecutorService.java
jbpm-wb-executor-service/jbpm-wb-executor-service-backend/src/main/java/org/jbpm/workbench/es/backend/server/DataSetDefsBootstrap.java
jbpm-wb-executor-service/jbpm-wb-executor-service-backend/src/main/java/org/jbpm/workbench/es/backend/server/RemoteExecutorServiceImpl.java
jbpm-wb-executor-service/jbpm-wb-executor-service-backend/src/main/java/org/jbpm/workbench/es/backend/server/RequestSummaryMapper.java
jbpm-wb-executor-service/jbpm-wb-executor-service-backend/src/test/java/org/jbpm/workbench/es/backend/server/RemoteExecutorServiceImplTest.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/jobdetails/JobDetailsPopup.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListPresenter.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListViewImpl.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/i18n/Constants.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/resources/org/jbpm/workbench/es/client/i18n/Constants.properties
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListPresenterTest.java

depends on https://github.com/kiegroup/droolsjbpm-integration/pull/1164

JBPM-6400 - KIE Server router - support for job operations

---

jbpm-wb-executor-service/jbpm-wb-executor-service-api/src/main/java/org/jbpm/workbench/es/model/RequestDataSetConstants.java
jbpm-wb-executor-service/jbpm-wb-executor-service-api/src/main/java/org/jbpm/workbench/es/model/RequestSummary.java
jbpm-wb-executor-service/jbpm-wb-executor-service-api/src/main/java/org/jbpm/workbench/es/service/ExecutorService.java
jbpm-wb-executor-service/jbpm-wb-executor-service-backend/src/main/java/org/jbpm/workbench/es/backend/server/DataSetDefsBootstrap.java
jbpm-wb-executor-service/jbpm-wb-executor-service-backend/src/main/java/org/jbpm/workbench/es/backend/server/RemoteExecutorServiceImpl.java
jbpm-wb-executor-service/jbpm-wb-executor-service-backend/src/main/java/org/jbpm/workbench/es/backend/server/RequestSummaryMapper.java
jbpm-wb-executor-service/jbpm-wb-executor-service-backend/src/test/java/org/jbpm/workbench/es/backend/server/RemoteExecutorServiceImplTest.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/jobdetails/JobDetailsPopup.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListPresenter.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListViewImpl.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/i18n/Constants.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/resources/org/jbpm/workbench/es/client/i18n/Constants.properties
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListPresenterTest.java

depends on https://github.com/kiegroup/droolsjbpm-integration/pull/1174

[7.3.x] JBPM-6400 - KIE Server router - support for job operations

---

jbpm-wb-forms/jbpm-wb-forms-api/src/main/java/org/jbpm/workbench/forms/service/providing/ProcessRenderingSettings.java
jbpm-wb-forms/jbpm-wb-forms-api/src/main/java/org/jbpm/workbench/forms/service/providing/RenderingSettings.java
jbpm-wb-forms/jbpm-wb-forms-api/src/main/java/org/jbpm/workbench/forms/service/providing/TaskRenderingSettings.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/FormServiceEntryPointImpl.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/KieWorkbenchFormsValuesProcessor.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormProvidingEngineTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormsValuesProcessorTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/ProcessFormsValuesProcessorTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/TaskFormValuesProcessorTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/process/AbstractStartProcessFormTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/task/AbstractTaskFormProvidingTest.java
jbpm-wb-forms/jbpm-wb-forms-modeler/jbpm-wb-forms-modeler-backend/src/main/java/org/jbpm/workbench/forms/modeler/backend/server/provider/FormModelerFormProvider.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/main/java/org/jbpm/workbench/pr/backend/server/RemoteProcessDocumentsServiceImpl.java
jbpm-wb-showcase/pom.xml

Copy of https://github.com/kiegroup/jbpm-wb/pull/873
@cristianonicolai @hasys could you take a look please?
https://github.com/kiegroup/jbpm/pull/982
https://github.com/kiegroup/kie-wb-common/pull/1163
https://github.com/kiegroup/jbpm-form-modeler/pull/143
https://github.com/kiegroup/jbpm-wb/pull/874

[7.3.x] JBPM-6047: Uploaded documents not visible on Documents tab on process Instance details

---

jbpm-wb-forms/jbpm-wb-forms-api/src/main/java/org/jbpm/workbench/forms/service/providing/ProcessRenderingSettings.java
jbpm-wb-forms/jbpm-wb-forms-api/src/main/java/org/jbpm/workbench/forms/service/providing/RenderingSettings.java
jbpm-wb-forms/jbpm-wb-forms-api/src/main/java/org/jbpm/workbench/forms/service/providing/TaskRenderingSettings.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/FormServiceEntryPointImpl.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/KieWorkbenchFormsValuesProcessor.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormProvidingEngineTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormsValuesProcessorTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/ProcessFormsValuesProcessorTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/TaskFormValuesProcessorTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/process/AbstractStartProcessFormTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/task/AbstractTaskFormProvidingTest.java
jbpm-wb-forms/jbpm-wb-forms-modeler/jbpm-wb-forms-modeler-backend/src/main/java/org/jbpm/workbench/forms/modeler/backend/server/provider/FormModelerFormProvider.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/main/java/org/jbpm/workbench/pr/backend/server/RemoteProcessDocumentsServiceImpl.java
jbpm-wb-showcase/pom.xml

@cristianonicolai @hasys could you take a look please?
https://github.com/kiegroup/jbpm/pull/981
https://github.com/kiegroup/kie-wb-common/pull/1160
https://github.com/kiegroup/jbpm-form-modeler/pull/142
https://github.com/kiegroup/jbpm-wb/pull/873

[8.0.x] JBPM-6047: Uploaded documents not visible on Documents tab on process Instance details

---

jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/dd/DDEditorServiceImpl.java
jbpm-wb-integration/jbpm-wb-integration-backend/src/test/java/org/jbpm/workbench/wi/backend/server/dd/DDEditorServiceTest.java

@mswiderski same comment on this fix as on the master branch pr.

[7.3.x] JBPM-6416 - Deployment descriptor validation fix

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml
jbpm-wb-showcase/pom.xml

See https://youtrack.jetbrains.com/issue/IDEA-166417

Use Errai's Wildfly distribution to allow upgrading Intellij

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml
jbpm-wb-showcase/pom.xml

See https://youtrack.jetbrains.com/issue/IDEA-166417

[7.3.x] Use Errai's Wildfly distribution to allow upgrading Intellij

---

jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/DashboardScreen.java
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/DashboardView.java
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/DashboardView.ui.xml
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/test/java/org/jbpm/dashboard/renderer/client/DashboardScreenTest.java

@cristianonicolai Can you review/approve please?

RHBPMS-4928: Broken page when selecting Process dashboard from task instances (7.3.x)

---

jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/DashboardScreen.java
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/DashboardView.java
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/DashboardView.ui.xml
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/test/java/org/jbpm/dashboard/renderer/client/DashboardScreenTest.java

@cristianonicolai Can you review/approve please?

RHBPMS-4928: Broken page when selecting Process dashboard from task instances

---

jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/DashboardKpis.java
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/test/java/org/jbpm/dashboard/renderer/client/TaskDashboardTest.java

@jhrcek @cristianonicolai Please can you review?
It fixes the first issue reported. As for the 2nd issue, see my last comment at JBPM-5833.

JBPM-5833: Strange units used for displaying data in charts in Process and Task Dashboard

---

jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/java/org/jbpm/workbench/ks/integration/KieServerDataSetProvider.java
jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/test/java/org/jbpm/workbench/ks/integration/KieServerDataSetProviderTest.java

depends on https://github.com/kiegroup/jbpm/pull/1042

JBPM-6514 - [Processes/Tasks dashboard] Charts by date show year only

---

jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseProjectServiceImpl.java
jbpm-wb-integration/jbpm-wb-integration-backend/src/main/resources/CaseWorkDefinitions.wid
jbpm-wb-integration/jbpm-wb-integration-backend/src/test/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseProjectServiceImplTest.java

depends on https://github.com/kiegroup/jbpm/pull/1041

JBPM-6509 - Support for sub cases both from within case and process

---

jbpm-wb-integration/jbpm-wb-integration-backend/src/test/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseProvisioningIT.java

- Fixes artifact not available in offline mode error

Update guice-servlet dependency in CaseProvisioningIT test

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/newcase/NewCaseInstancePresenter.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/newcase/NewCaseInstanceViewImpl.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/newcase/NewCaseInstancePresenterTest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/util/CaseRolesValidationsTest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/util/CommaListValuesConverterTest.java

@cristianonicolai @nmirasch Extended tests around loading case roles and their assignment when a case instance is being started.
Did also a small re-factoring of existing tests around case roles validation, which should be more concrete when it comes to what they are testing in presenter logic.

[JBPM-6678] Case Roles: Tests for case roles assignment at case start

---

jbpm-wb-showcase/pom.xml

Small pom changes required by kiegroup/appformer#125
@pefernan @jhrcek Can you approve please :-)?

AF-930: [Layout Editor] Use dock panels to increase the editor content area

---

jbpm-wb-integration/jbpm-wb-integration-api/src/main/java/org/jbpm/workbench/wi/casemgmt/service/CaseProjectService.java
jbpm-wb-integration/jbpm-wb-integration-backend/pom.xml
jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseDemoProvisioningService.java
jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseProjectServiceImpl.java
jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/dd/DDConfigUpdater.java
jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/dd/DDConfigUpdaterHelper.java
jbpm-wb-integration/jbpm-wb-integration-backend/src/test/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseProjectServiceImplTest.java
jbpm-wb-integration/jbpm-wb-integration-backend/src/test/java/org/jbpm/workbench/wi/backend/server/dd/DDConfigUpdaterTest.java
jbpm-wb-integration/jbpm-wb-integration-client/pom.xml
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/handlers/NewCaseProjectHandler.java
jbpm-wb-integration/jbpm-wb-integration-client/src/test/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/DeploymentDescriptorEditorPresenterTest.java
jbpm-wb-integration/jbpm-wb-integration-client/src/test/java/org/jbpm/workbench/wi/client/handlers/NewCaseProjectHandlerTest.java
jbpm-wb-showcase/pom.xml
jbpm-wb-showcase/src/main/java/org/jbpm/workbench/client/perspectives/AdministrationPerspective.java
jbpm-wb-showcase/src/main/java/org/jbpm/workbench/server/impl/AppSetup.java
jbpm-wb-showcase/src/main/resources/org/jbpm/workbench/jBPMShowcase.gwt.xml

WorkspaceProjectContext from backend. Pass space as parameter.

AF-648 : Change Project from a folder in a repo to a repository

---

jbpm-wb-showcase/pom.xml

Related to:
https://github.com/kiegroup/optaplanner-wb/pull/250
https://github.com/kiegroup/drools-wb/pull/799
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/692
https://github.com/kiegroup/kie-wb-distributions/pull/685
https://github.com/kiegroup/kie-wb-playground/pull/46
https://github.com/kiegroup/jbpm-wb/pull/980
https://github.com/kiegroup/kie-wb-common/pull/1411

[RHDM-349]: Added new playground dependency

---

jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/TaskListPresenter.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/resources/i18n/Constants.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/resources/org/jbpm/workbench/ht/client/resources/i18n/Constants.properties
jbpm-wb-showcase/src/main/java/org/jbpm/workbench/client/ShowcaseEntryPoint.java
jbpm-wb-showcase/src/main/java/org/jbpm/workbench/client/i18n/Constants.java
jbpm-wb-showcase/src/main/resources/org/jbpm/workbench/client/i18n/Constants.properties
jbpm-wb-showcase/src/test/java/org/jbpm/workbench/client/ShowcaseEntryPointTest.java

Depends on https://github.com/kiegroup/kie-wb-common/pull/1452

JBPM-6887 - Rename Task Lists to Task Inbox

---

jbpm-console-ng-workbench-integration/jbpm-console-ng-workbench-integration-client/src/main/java/org/jbpm/console/ng/wi/client/editors/deployment/descriptor/DeploymentDescriptorEditorPresenter.java
jbpm-console-ng-workbench-integration/jbpm-console-ng-workbench-integration-client/src/test/java/org/jbpm/console/ng/wi/client/editors/deployment/descriptor/DeploymentDescriptorEditorPresenterTest.java

https://issues.jboss.org/browse/AF-1079
These PRs change the service visibilities to protected for testing purposes. Not how I would like to do them, but the other option is to do even more refactoring and since this is an older branch, I don't think it is worth the risk.
https://github.com/AppFormer/uberfire-extensions/pull/324
https://github.com/dashbuilder/dashbuilder/pull/419
https://github.com/kiegroup/kie-wb-common/pull/1489
https://github.com/kiegroup/drools-wb/pull/825
https://github.com/kiegroup/jbpm-wb/pull/992

[6.5.x]  AF-1079 : Empty 'Validation errors' popup in Decision/Business Central

---

jbpm-wb-showcase/pom.xml

Hello @romartin @hasys would you mind review this PR?
Thanks
depends on:
https://github.com/kiegroup/appformer/pull/241
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/721
https://github.com/kiegroup/kie-wb-common/pull/1504

JBPM-6876: Stunner - easy way to migrate from Stunner to current Designer

---

jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/list/AbstractMultiGridView.java

[7.7.x] JBPM-7003 - Update page size selector style to match PatternFly dropdown

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/src/test/java/org/jbpm/workbench/cm/backend/server/CaseInstanceMapperTest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/stages/CaseStageItemViewImpl.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/stages/CaseStagesPresenter.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/stages/CaseStagesViewImpl.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/stages/CaseStagesPresenterTest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/util/AbstractCaseInstancePresenterTest.java

@cristianonicolai @nmirasch Have done a small re-factoring to accommodate a couple of more unit tests and have done a small cleanup here and there along the way.

JBPM-7113 Case Stages: Review tests

---

jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/quicknewjob/NewJobViewImpl.java

Issue: [JBPM-6781](https://issues.jboss.org/browse/JBPM-6781)

JBPM-6781: reposition date picker popup

---

jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/java/org/jbpm/workbench/ks/integration/KieServerIntegration.java
jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/test/java/org/jbpm/workbench/ks/integration/KieServerIntegrationClientsTest.java

depends on https://github.com/kiegroup/droolsjbpm-integration/pull/1422

RHPAM-687 - Immutable KIE servers cannot be directly monitored

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-api/src/main/java/org/jbpm/workbench/cm/model/CaseActionSummary.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/pom.xml
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/src/test/java/org/jbpm/workbench/cm/backend/server/RemoteCaseManagementServiceImplTest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/actions/CaseActionItemView.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/actions/CaseActionsListViewImpl.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/actions/CaseActionsPresenter.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/actions/CaseActionsViewImpl.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/actions/ActionsPresenterTest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/stages/CaseStagesPresenterTest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/util/AbstractCaseInstancePresenterTest.java

@cristianonicolai @nmirasch Cherry-picking to 7.7.x branch.

[JBPM-7115] Case audit: Review tests

---

jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/test/java/org/jbpm/workbench/pr/backend/server/RemoteProcessServiceImplTest.java

@cristianonicolai @nmirasch Cherry-picking to 7.7.x branch.

[7.7.x] [JBPM-7139] Process Instances: Add backend tests for bulk actions

---

jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseProjectServiceImpl.java
jbpm-wb-integration/jbpm-wb-integration-backend/src/test/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseProjectServiceImplTest.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/handlers/NewCaseProjectHandler.java
jbpm-wb-integration/jbpm-wb-integration-client/src/test/java/org/jbpm/workbench/wi/client/handlers/NewCaseProjectHandlerTest.java

@mswiderski this puts back the use of configureCaseProjectCallback which was removed in commit 
https://github.com/kiegroup/jbpm-wb/commit/57c1fd7350f4f7f06c6037aeb3f4dd0f9e7102d7#diff-f7a96202b473a4c949f4d3fd20642d1d
and also fixes the path issues in creating the "/.caseproject" dot file

JBPM-7161 - Fix new case project configuration

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/actions/CaseActionItemView.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/actions/CaseActionsPresenter.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/actions/NewActionViewImpl.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/actions/ActionsPresenterTest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/util/AbstractCaseInstancePresenterTest.java

@cristianonicolai @nmirasch Re-factored and added more tests in this area.
Also, fixed a small issue - each time the case view was refreshed, the case stage and sub-process options were added again when starting a dynamic user task/sub-process, like this:

[JBPM-7177] Dynamic tasks in case stages: Review tests

---

jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/handlers/NewCaseProjectHandler.java

* https://github.com/kiegroup/kie-wb-common/pull/1644
* https://github.com/kiegroup/jbpm-wb/pull/1073

AF-1130: Remove from create assets list Project, Case Project and Import Asset

---

jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/handlers/NewCaseProjectHandler.java

Cherry-picked from https://github.com/kiegroup/jbpm-wb/pull/1073
* https://github.com/kiegroup/kie-wb-common/pull/1684
* https://github.com/kiegroup/jbpm-wb/pull/1084

[7.7.x] AF-1130: Remove from create assets list Project, Case Project and Import Asset

---

jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/quicknewjob/NewJobViewImpl.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/quicknewjob/NewJobViewImplTest.java

Issue: [JBPM-6785](https://issues.jboss.org/browse/JBPM-6785)

JBPM-6785: redraw table to show empty widget

---

jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/quicknewjob/NewJobViewImpl.java

Cherry pick https://github.com/kiegroup/jbpm-wb/pull/1015 into 7.7.x

[7.7.x] RHPAM-871: reposition date picker popup

---

jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/quicknewjob/NewJobViewImpl.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/quicknewjob/NewJobViewImplTest.java

Cherry pick https://github.com/kiegroup/jbpm-wb/pull/1033 into 7.7.x

[7.7.x] RHPAM-869: redraw table to show empty widget

---

jbpm-wb-forms/jbpm-wb-forms-backend/pom.xml
jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/ProcessFormsValuesProcessor.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/TaskFormValuesProcessor.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormsValuesProcessorWithWrongTypesTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/ProcessFormsValuesProcessorWithWrongValuesTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/TaskFormValuesProcessorWithWrongTypesTest.java

Copy of https://github.com/kiegroup/jbpm-wb/pull/1100
@kkufova @cristianonicolai  could you please review?
This PR si part of an ensemble, merge with:
https://github.com/kiegroup/kie-wb-common/pull/1711
https://github.com/kiegroup/jbpm-wb/pull/1101

[7.7.x] RHPAM-850: Fix Form Generation issues when using unsupported types 

---

jbpm-wb-forms/jbpm-wb-forms-backend/pom.xml
jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/ProcessFormsValuesProcessor.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/TaskFormValuesProcessor.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormsValuesProcessorWithWrongTypesTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/ProcessFormsValuesProcessorWithWrongValuesTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/TaskFormValuesProcessorWithWrongTypesTest.java

@cristianonicolai @kkufova could you please review?
https://github.com/kiegroup/kie-wb-common/pull/1709
https://github.com/kiegroup/jbpm-wb/pull/1100
@kkufova you can find a reproducer here: https://github.com/pefernan/RHPAM-850-form-generation-unsupported-types

RHPAM-850: Fix Form Generation issues when using unsupported types

---

jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/handlers/NewCaseProjectHandler.java
jbpm-wb-integration/jbpm-wb-integration-client/src/test/java/org/jbpm/workbench/wi/client/handlers/NewCaseProjectHandlerTest.java

Assembly:
- https://github.com/kiegroup/jbpm-wb/pull/1104
- https://github.com/kiegroup/kie-wb-common/pull/1717

[7.7.x] RHPAM-542 - New Case Project uses old dialog

---

jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/handlers/NewCaseProjectHandler.java
jbpm-wb-integration/jbpm-wb-integration-client/src/test/java/org/jbpm/workbench/wi/client/handlers/NewCaseProjectHandlerTest.java

Assembly:
- https://github.com/kiegroup/jbpm-wb/pull/1105
- https://github.com/kiegroup/kie-wb-common/pull/1718

RHPAM-542 - New Case Project uses old dialog

---

jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskdetailsmulti/TaskDetailsMultiViewImpl.java

Removed onResize form work tab to set manually the height

JBPM-7214: Task details 'Work' tab displays scroll when it's not needed

---

jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/quicknewjob/NewJobPresenterTest.java

cherry-pick the test fix to the master

Fix failing test in NewJobPresenterTest

---

jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/FormServiceEntryPointImpl.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/FormServiceEntryPointImplTest.java

Backport of https://github.com/kiegroup/jbpm-wb/pull/1111
@cristianonicolai could you please take a look?

[7.7.x] JBPM-7229: Tasks: User task without generated form can't be completed

---

jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/FormServiceEntryPointImpl.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/FormServiceEntryPointImplTest.java

@cristianonicolai could you please take a look?

JBPM-7229: Tasks: User task without generated form can't be completed

---

jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/items/NamedObjectItemPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/items/ObjectItemPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/items/ParametersModal.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/items/ParametersModalView.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/configuration/DeploymentsConfigurationPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/environmententries/DeploymentsEnvironmentEntriesPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/eventlisteners/DeploymentsEventListenersPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/globals/DeploymentsGlobalsPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/marshallingstrategies/DeploymentsMarshallingStrategiesPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/remoteableclasses/DeploymentsRemoteableClassesPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/remoteableclasses/RemoteableClassListItemPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/requiredroles/DeploymentsRequiredRolesPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/requiredroles/RequiredRolesListItemPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/taskeventlisteners/DeploymentsTaskEventListenersPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/workitemhandlers/DeploymentsWorkItemHandlersPresenter.java

https://issues.jboss.org/browse/DROOLS-2526
Bundle:
https://github.com/kiegroup/kie-wb-common/pull/1745
https://github.com/kiegroup/jbpm-wb/pull/1115

[7.7.x] DROOLS-2526 : [Test Scenario][IE] Can't be run

---

jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/items/NamedObjectItemPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/items/ObjectItemPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/items/ParametersModal.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/items/ParametersModalView.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/configuration/DeploymentsConfigurationPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/environmententries/DeploymentsEnvironmentEntriesPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/eventlisteners/DeploymentsEventListenersPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/globals/DeploymentsGlobalsPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/marshallingstrategies/DeploymentsMarshallingStrategiesPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/remoteableclasses/DeploymentsRemoteableClassesPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/remoteableclasses/RemoteableClassListItemPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/requiredroles/DeploymentsRequiredRolesPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/requiredroles/RequiredRolesListItemPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/taskeventlisteners/DeploymentsTaskEventListenersPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/workitemhandlers/DeploymentsWorkItemHandlersPresenter.java

(cherry picked from commit 004bbed9e89089455d6009b01d8f382c9caa079f)
https://issues.jboss.org/browse/DROOLS-2526
Bundle:
https://github.com/kiegroup/kie-wb-common/pull/1744
https://github.com/kiegroup/jbpm-wb/pull/1117

DROOLS-2526 : [Test Scenario][IE] Can't be run

---

jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/tasklogs/TaskLogsViewImpl.java

Completes the fix https://github.com/kiegroup/jbpm/pull/1239

RHPAM-609: Tasks First Due Date update writes null to task log

---

jbpm-wb-integration/jbpm-wb-integration-backend/pom.xml

depends on https://github.com/kiegroup/jbpm/pull/1233

JBPM-7323 - CMMN excution support for case management

---

jbpm-wb-forms/jbpm-wb-forms-client/pom.xml
jbpm-wb-forms/jbpm-wb-forms-client/src/main/java/org/jbpm/workbench/forms/client/display/standalone/FormDisplayPerspective.java
jbpm-wb-forms/jbpm-wb-forms-client/src/main/java/org/jbpm/workbench/forms/client/display/standalone/StandaloneConstants.java
jbpm-wb-forms/jbpm-wb-forms-client/src/main/java/org/jbpm/workbench/forms/client/display/standalone/StandaloneProcessFormDisplayScreen.java
jbpm-wb-forms/jbpm-wb-forms-client/src/main/java/org/jbpm/workbench/forms/client/display/standalone/StandaloneTaskFormDisplayScreen.java
jbpm-wb-forms/jbpm-wb-forms-client/src/test/java/org/jbpm/workbench/forms/client/display/standalone/StandaloneProcessFormDisplayScreenTest.java
jbpm-wb-forms/jbpm-wb-forms-client/src/test/java/org/jbpm/workbench/forms/client/display/standalone/StandaloneTaskFormDisplayScreenTest.java

I had to add them back do to an escalation from a customer...
@jsoltes @cristianonicolai could you please review?

[7.7.x] RHPAM-1299: Recover standalone perspectives for process / task forms

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/list/CaseInstanceViewImpl.html
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/list/CaseInstanceViewImpl.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/overview/CaseOverviewViewImpl.html

@cristianonicolai  Please review it.

JBPM-7314 Case actions and case status should be aligned

---

jbpm-wb-forms/jbpm-wb-forms-client/pom.xml
jbpm-wb-forms/jbpm-wb-forms-client/src/main/java/org/jbpm/workbench/forms/client/display/standalone/FormDisplayPerspective.java
jbpm-wb-forms/jbpm-wb-forms-client/src/main/java/org/jbpm/workbench/forms/client/display/standalone/StandaloneConstants.java
jbpm-wb-forms/jbpm-wb-forms-client/src/main/java/org/jbpm/workbench/forms/client/display/standalone/StandaloneProcessFormDisplayScreen.java
jbpm-wb-forms/jbpm-wb-forms-client/src/main/java/org/jbpm/workbench/forms/client/display/standalone/StandaloneTaskFormDisplayScreen.java
jbpm-wb-forms/jbpm-wb-forms-client/src/test/java/org/jbpm/workbench/forms/client/display/standalone/StandaloneProcessFormDisplayScreenTest.java
jbpm-wb-forms/jbpm-wb-forms-client/src/test/java/org/jbpm/workbench/forms/client/display/standalone/StandaloneTaskFormDisplayScreenTest.java

Copy of https://github.com/kiegroup/jbpm-wb/pull/1161
@jsoltes @cristianonicolai could you please review?

JBPM-7387: Recover standalone perspectives for process / task forms

---

jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/definition/list/ProcessDefinitionListViewImpl.java

@cristianonicolai  Please review it.

JBPM-5291 Process Definitions: Project and Deployment Name coupled

---

jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/FormServiceEntryPointImplTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormProvidingEngineTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormsValuesProcessorTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormsValuesProcessorWithWrongTypesTest.java

Refactor required by https://github.com/kiegroup/kie-wb-common/pull/1864
@cristianonicolai @jsoltes could you please review?
This PR is part of an ensemble, merge with:
https://github.com/kiegroup/kie-wb-common/pull/1864
https://github.com/kiegroup/jbpm-wb/pull/1148

JBPM-6918 (RHPAM-453): Some values filled in the Multiple Subform don't get transfered to the next task.

---

jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/FormServiceEntryPointImplTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormProvidingEngineTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormsValuesProcessorTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormsValuesProcessorWithWrongTypesTest.java

Backport of https://github.com/kiegroup/jbpm-wb/pull/1148
@jsoltes @cristianonicolai could you please review?
This PR is part of an ensemble, merge with:
https://github.com/kiegroup/kie-wb-common/pull/1879
https://github.com/kiegroup/jbpm-wb/pull/1150

[7.7.x] JBPM-6918: Some values filled in the Multiple Subform don't get transfered to the next task.

---

jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/dataset/AbstractDataSetReadyCallback.java
jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/dataset/DataSetAwareSelect.java
jbpm-wb-common/jbpm-wb-common-client/src/test/java/org/jbpm/workbench/common/client/dataset/AbstractDataSetReadyCallbackTest.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/items/ParametersModal.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/items/ParametersModalView.java
jbpm-wb-showcase/src/main/java/org/jbpm/workbench/client/ShowcaseEntryPoint.java
jbpm-wb-showcase/src/test/java/org/jbpm/workbench/client/ShowcaseEntryPointTest.java

Related:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/770
https://github.com/errai/errai/pull/350
https://github.com/kiegroup/appformer/pull/404
https://github.com/kiegroup/kie-wb-common/pull/1925
https://github.com/kiegroup/drools-wb/pull/878
https://github.com/kiegroup/jbpm-wb/pull/1162
https://github.com/kiegroup/optaplanner-wb/pull/288
https://github.com/kiegroup/kie-wb-distributions/pull/773

AF-1226: Improve error handling displaying additional info to the GenericErrorPopup

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/list/CaseInstanceListSearchViewImpl.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/list/CaseInstanceListViewImpl.html
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/resources/org/jbpm/workbench/cm/client/resources/i18n/Constants.properties
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/list/CaseInstanceListSearchViewTest.java

https://issues.jboss.org/browse/RHPAM-1183
PR with cherry-pick of https://github.com/kiegroup/jbpm-wb/pull/1142

JBPM-7313: Case List: Should have refresh option (#1142)

---

jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseDemoProvisioningService.java

Related to: 
* https://github.com/kiegroup/kie-wb-common/pull/2060

[AF-1254]: LibraryService import replaced with new ProjectImportService

---

jbpm-wb-common/jbpm-wb-common-api/pom.xml
jbpm-wb-common/jbpm-wb-common-api/src/main/java/org/jbpm/workbench/common/preferences/ItemPerPageValidator.java
jbpm-wb-common/jbpm-wb-common-api/src/main/java/org/jbpm/workbench/common/preferences/ManagePreferences.java
jbpm-wb-common/jbpm-wb-common-api/src/main/resources/org/jbpm/workbench/common/JbpmWorkbenchCommonAPI.gwt.xml
jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/list/AbstractListView.java
jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/list/AbstractMultiGridPresenter.java
jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/list/AbstractMultiGridView.java
jbpm-wb-common/jbpm-wb-common-client/src/main/resources/org/jbpm/workbench/common/client/resources/i18n/Constants.properties
jbpm-wb-common/jbpm-wb-common-client/src/test/java/org/jbpm/workbench/common/client/list/AbstractMultiGridViewTest.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/errorlist/ExecutionErrorListPresenter.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/errorlist/ExecutionErrorListViewImpl.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListPresenter.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListViewImpl.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/errorlist/ExecutionErrorListPresenterTest.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListPresenterTest.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/AbstractTaskListPresenter.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/AbstractTaskListView.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/test/java/org/jbpm/workbench/ht/client/editors/taskslist/AbstractTaskListPresenterTest.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/definition/list/ProcessDefinitionListViewImpl.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListPresenter.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListViewImpl.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/definition/list/ProcessDefinitionListViewTest.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListPresenterTest.java

Depends on https://github.com/kiegroup/kie-wb-common/pull/2082

JBPM-7696 - Use default preferences for paging option in manage section

---

jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/ProcessFormsValuesProcessor.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/TaskFormValuesProcessor.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormsValuesProcessorWithWrongTypesTest.java

Adding changes from https://github.com/kiegroup/kie-wb-common/pull/2205
@jsoltes  @cristianonicolai could you please take a look?
https://github.com/kiegroup/kie-wb-common/pull/2205
https://github.com/kiegroup/jbpm-wb/pull/1222

AF-1632: [Form Modeler] Error appears after clicking New Instance in MultipleSubForm Field properties modal window

---

jbpm-wb-showcase/pom.xml

Related PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/798
* https://github.com/kiegroup/appformer/pull/434
* https://github.com/kiegroup/kie-wb-common/pull/2037
* https://github.com/kiegroup/drools-wb/pull/910
* https://github.com/kiegroup/jbpm-wb/pull/1187
* https://github.com/kiegroup/optaplanner-wb/pull/294
* https://github.com/kiegroup/kie-wb-distributions/pull/792

[AF-1220]: Added infinispan dependency

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/src/main/resources/org/jbpm/workbench/cm/jBPMCaseManagement.gwt.xml
jbpm-wb-showcase/pom.xml
jbpm-wb-showcase/src/main/resources/org/jbpm/workbench/jBPMShowcase.gwt.xml

AF-1275: SSH Keystore backend
AF-1274: SSH Keystore UI
AF-1277: Integrate SSH Keystore with VFS SSH
Adding missing dependencies...
@cristianonicolai @ederign could you please take a look?
https://github.com/kiegroup/appformer/pull/492
https://github.com/kiegroup/kie-wb-common/pull/2177
https://github.com/kiegroup/kie-wb-distributions/pull/829
https://github.com/kiegroup/drools-wb/pull/959
https://github.com/kiegroup/jbpm-wb/pull/1215
https://github.com/kiegroup/optaplanner-wb/pull/308
https://github.com/kiegroup/kie-docs/pull/1156

AF-1424: Support SSH keystore with workbench

---

jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/resources/default-query-definitions.json

[7.14.x] JBPM-7920 - Use processInstanceId column for join on ProcessInstanceLog

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-api/src/main/java/org/jbpm/workbench/cm/util/CaseInstanceSearchRequest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/details/CaseDetailsViewImpl.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/list/CaseInstanceListPresenter.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/list/CaseInstanceListSearchViewImpl.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/list/CaseInstanceListViewImpl.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/list/CaseInstanceViewImpl.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/util/CaseStatusLabelConverter.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/list/CaseInstanceListPresenterTest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/util/CaseStatusConverterTest.java

Depends on https://github.com/kiegroup/appformer/pull/567

JBPM-8046 - Select inputs should be initialized before model is set

---

jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/log/ProcessInstanceLogItemView.java

Use the item view hascode to generate details panel unique id and

JBPM-8057: Process instance log details panel with unique id

---

jbpm-wb-showcase/pom.xml

Adding the new chart implementation based on C3 as a dependency.

AF-1655: Adding C3 dependency

---

jbpm-wb-forms/jbpm-wb-forms-api/src/main/java/org/jbpm/workbench/forms/display/api/KieWorkbenchFormRenderingSettings.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/KieWorkbenchFormsValuesProcessor.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormsValuesProcessorWithWrongTypesTest.java
jbpm-wb-forms/jbpm-wb-forms-client/pom.xml
jbpm-wb-forms/jbpm-wb-forms-client/src/main/java/org/jbpm/workbench/forms/client/GenericFormsClientEntryPoint.java
jbpm-wb-forms/jbpm-wb-forms-client/src/main/java/org/jbpm/workbench/forms/client/display/KieWorkbenchFormsHumanTaskDisplayer.java
jbpm-wb-forms/jbpm-wb-forms-client/src/main/java/org/jbpm/workbench/forms/client/display/KieWorkbenchFormsStartProcessDisplayer.java
jbpm-wb-forms/jbpm-wb-forms-client/src/main/java/org/jbpm/workbench/forms/client/display/displayer/KieWorkbenchFormDisplayer.java
jbpm-wb-forms/jbpm-wb-forms-client/src/main/java/org/jbpm/workbench/forms/client/display/displayer/KieWorkbenchFormDisplayerView.java
jbpm-wb-forms/jbpm-wb-forms-client/src/main/java/org/jbpm/workbench/forms/client/display/displayer/KieWorkbenchFormDisplayerViewImpl.html
jbpm-wb-forms/jbpm-wb-forms-client/src/main/java/org/jbpm/workbench/forms/client/display/displayer/KieWorkbenchFormDisplayerViewImpl.java
jbpm-wb-forms/jbpm-wb-forms-client/src/main/resources/org/jbpm/workbench/forms/client/i18n/FormsConstants.properties
jbpm-wb-forms/jbpm-wb-forms-client/src/main/resources/org/jbpm/workbench/forms/client/i18n/FormsConstants_es.properties
jbpm-wb-forms/jbpm-wb-forms-client/src/main/resources/org/jbpm/workbench/forms/client/i18n/FormsConstants_ja.properties
jbpm-wb-forms/jbpm-wb-forms-client/src/test/java/org/jbpm/workbench/forms/client/display/displayer/KieWorkbenchFormDisplayerTest.java

Backport of https://github.com/kiegroup/jbpm-wb/pull/1261
https://github.com/kiegroup/kie-wb-common/pull/2358
https://github.com/kiegroup/jbpm-wb/pull/1263
https://github.com/kiegroup/kie-docs/pull/1320

[7.14.x] JBPM-7997: garbled message in start process form when OS locale is Japanese

---

jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/handlers/NewCaseProjectHandler.java
jbpm-wb-integration/jbpm-wb-integration-client/src/test/java/org/jbpm/workbench/wi/client/handlers/NewCaseProjectHandlerTest.java

* https://github.com/kiegroup/appformer/pull/588
* https://github.com/kiegroup/kie-wb-common/pull/2365
* https://github.com/kiegroup/jbpm-wb/pull/1266

AF-1639: Permission to read/write spaces and projects now should be based in their collaborators

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml

PR set:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/900 (Please comment on this PR if you have any questions)
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/352
* https://github.com/kiegroup/drools/pull/2191
* https://github.com/kiegroup/jbpm/pull/1394
* https://github.com/kiegroup/optaplanner/pull/469
* https://github.com/kiegroup/droolsjbpm-integration/pull/1667
* https://github.com/kiegroup/appformer/pull/574
* https://github.com/kiegroup/optaplanner-wb/pull/319
* https://github.com/kiegroup/jbpm-wb/pull/1257
* https://github.com/kiegroup/kie-wb-distributions/pull/858
* https://github.com/kiegroup/optaweb-employee-rostering/pull/215

Align JAXB and JAXWS APIs with Wildfly

---

jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/details/ProcessInstanceDetailsPresenter.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/details/ProcessInstanceDetailsViewImpl.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/diagram/NodeCounterView.html
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/diagram/NodeCounterView.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/diagram/ProcessInstanceDiagramPresenter.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/diagram/ProcessInstanceDiagramView.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/diagram/ProcessInstanceDiagramViewImpl.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/resources/org/jbpm/workbench/pr/client/resources/i18n/Constants.properties
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/instance/details/ProcessInstanceDetailsPresenterTest.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/instance/diagram/ProcessInstanceDiagramPresenterTest.java

Depends on https://github.com/kiegroup/appformer/pull/612

JBPM-8114 - Add node instance badge counter in process diagram

---

jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/diagram/ProcessDiagramWidgetViewImpl.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/diagram/ProcessDiagramWidgetViewTest.java

Depends on https://github.com/kiegroup/appformer/pull/632

JBPM-8216 - Filter SVG container nodes

---

jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/list/AbstractMultiGridView.java
jbpm-wb-common/jbpm-wb-common-client/src/test/java/org/jbpm/workbench/common/client/list/AbstractMultiGridViewTest.java

configure views to show an scroll when there aren't enough space to show the visible columns

JBPM-8232: Horizontal scrollbars missing in task inbox

---

jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/diagram/ProcessDiagramPresenter.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/diagram/ProcessDiagramWidgetView.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/diagram/ProcessDiagramWidgetViewImpl.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/diagram/ProcessInstanceDiagramViewImpl.java

Cherry pick https://github.com/kiegroup/jbpm-wb/pull/1298

[7.18.x] JBPM-8263 - Handle missing SVG image

---

jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/java/org/jbpm/workbench/ks/integration/KieServerIntegration.java
jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/test/java/org/jbpm/workbench/ks/integration/KieServerIntegrationClientsTest.java

cherry pick from 3893396bbf2d3f187ec0bfd8a15ee141a2042786

[7.18.x] JBPM-8276 - Create Kie Server clients async to not block deployment  (backport)

---

jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/diagram/ProcessDiagramWidgetViewTest.java

depends on https://github.com/kiegroup/appformer/pull/646

AF-1663: Fix tests to adapt to D3 changes

---

jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/AbstractTaskListPresenter.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/AbstractTaskListView.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/resources/i18n/Constants.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/resources/org/jbpm/workbench/ht/client/resources/i18n/Constants.properties
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/test/java/org/jbpm/workbench/ht/client/editors/taskslist/AbstractTaskListPresenterTest.java

@cristianonicolai Please view it.

JBPM-8358 Claim task in Task Inbox should open Task details page

---

jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/casemgmt/CMMNEditorPresenter.java

https://issues.jboss.org/browse/DROOLS-3425
https://github.com/kiegroup/kie-wb-common/pull/2503
https://github.com/kiegroup/drools-wb/pull/1082
https://github.com/kiegroup/jbpm-designer/pull/837
https://github.com/kiegroup/jbpm-wb/pull/1309
https://github.com/kiegroup/optaplanner-wb/pull/327

DROOLS-3425 : Unexpected behavior of docks when multiple editors are opened

---

jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/filters/saved/SavedFiltersPresenter.java
jbpm-wb-common/jbpm-wb-common-client/src/test/java/org/jbpm/workbench/common/client/filters/saved/SavedFiltersPresenterTest.java
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/AbstractDashboard.java
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/ProcessDashboard.java
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/TaskDashboard.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/errorlist/ExecutionErrorListPresenter.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/errorlist/ExecutionErrorListSavedFiltersPresenter.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/requestlist/JobListSavedFiltersPresenter.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListPresenter.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskdetailsmulti/TaskDetailsMultiPresenter.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/AbstractTaskListPresenter.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/TaskAdminListPresenter.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/TaskAdminListSavedFiltersPresenter.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/TaskListPresenter.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/TaskListSavedFiltersPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/casemgmt/CMMNEditorPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/CustomizedSettingsSections.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/handlers/NewCaseProjectHandler.java
jbpm-wb-integration/jbpm-wb-integration-client/src/test/java/org/jbpm/workbench/wi/client/handlers/NewCaseProjectHandlerTest.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/definition/details/ProcessDefinitionDetailsPresenter.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/definition/list/ProcessDefinitionListPresenter.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/details/ProcessInstanceDetailsPresenter.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListPresenter.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListSavedFiltersPresenter.java

* https://github.com/kiegroup/appformer/pull/665
* https://github.com/kiegroup/kie-wb-common/pull/2538
* https://github.com/kiegroup/drools-wb/pull/1095
* https://github.com/kiegroup/jbpm-designer/pull/843
* https://github.com/kiegroup/jbpm-wb/pull/1319
* https://github.com/kiegroup/optaplanner-wb/pull/330

AF-1674: Role-based access to branches in the Workbench

---

jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/FormServiceEntryPointImpl.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/conversion/TaskDataConverterUtil.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/conversion/TaskDataConverterUtilTest.java

@domhanak @cristianonicolai @nmirasch could you please take a look?

JBPM-8447: Unable to display task with task input equal to constant

---

jbpm-wb-showcase/pom.xml
jbpm-wb-showcase/src/main/resources/org/jbpm/workbench/jBPMShowcase.gwt.xml

Related PRs:
kiegroup/kie-wb-distributions#903
kiegroup/optaplanner-wb#332
https://github.com/kiegroup/drools-wb/pull/1101
kiegroup/kie-wb-common#2549
kiegroup/appformer#670

AF-1774: Removing GChartsRenderer (Google Charts)

---

jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/workitem/RepositoryStorageVFSImpl.java

Several things happen in this PR that can't be split in several commits:
All the information about spaces and repositories used to live in system.git project. That project makes that every change that was need to be done locks repository for all users. 
Now, all the information about each space is stored inside config.git in every space. So lock will happen only for that space and not for the whole file system. Also migration tool was modified to include previous changes.
When you delete a Space or Repository, they are marked to be deleted. User will continue working as it was used to. Nothing from user perspectiva but they way that deleted spaces are shown. 
* A deleted Repository disappear from Library View and is marked to be deleted with a flag in config.git
* A deleted Space doesn't …

[AF-1792]  Migration of space information from system.git to config.git + HA improvements

---

jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/filters/basic/BasicFiltersViewImpl.html
jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/filters/basic/BasicFiltersViewImpl.java

@cristianonicolai Please review it .

JBPM-8730 Filters - numeric field hint not in sync with implementation

---

jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/list/AbstractListPresenter.java
jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/list/event/DeselectAllItemsEvent.java
jbpm-wb-common/jbpm-wb-common-client/src/test/java/org/jbpm/workbench/common/client/list/AbstractListPresenterTest.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/errorlist/ExecutionErrorListPresenter.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/errorlist/ExecutionErrorListViewImpl.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListPresenter.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListViewImpl.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/errorlist/ExecutionErrorListPresenterTest.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListPresenterTest.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/AbstractTaskListPresenter.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/AbstractTaskListView.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/popup/TasksReassignmentPresenter.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/test/java/org/jbpm/workbench/ht/client/editors/taskslist/AbstractTaskListPresenterTest.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/test/java/org/jbpm/workbench/ht/client/editors/taskslist/popup/TasksReassignmentPresenterTest.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListPresenter.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListViewImpl.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/signal/ProcessInstanceSignalPresenter.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListPresenterTest.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListViewImplTest.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/instance/signal/ProcessInstanceSignalPresenterTest.java

…the operation
Added BulkActionPerformedEvent that is fired when a bulk operation that requires a data introduction popup is performed, to allow unselect the checkboxes after the operation is done

JBPM-8775: Bulk task reassignment and bulk PI signaling reset checkboxes before finishing... 

---

jbpm-wb-showcase/pom.xml
jbpm-wb-showcase/src/main/resources/org/jbpm/workbench/jBPMShowcase.gwt.xml

Part of an ensemble
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1066
kiegroup/appformer#807
kiegroup/kie-wb-common#2917
https://github.com/kiegroup/drools-wb/pull/1235
https://github.com/kiegroup/optaplanner-wb/pull/347
https://github.com/kiegroup/kie-wb-distributions/pull/964

AF-2125: Adding  dependencies removed from widgets core

---

pom.xml

https://issues.jboss.org/browse/DROOLS-4563
parent PR kiegroup/droolsjbpm-build-bootstrap/pull/1075

DROOLS-4563: managing validation api for GWT components

---

jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseDemoProvisioningService.java
jbpm-wb-showcase/pom.xml
jbpm-wb-showcase/src/main/resources/org/jbpm/workbench/jBPMShowcase.gwt.xml

Main PR: https://github.com/kiegroup/kie-wb-common/pull/2991
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1092
* https://github.com/kiegroup/kie-wb-common/pull/2991
* https://github.com/kiegroup/jbpm-wb/pull/1401
* https://github.com/kiegroup/drools-wb/pull/1256
* https://github.com/kiegroup/kie-wb-distributions/pull/986
* https://github.com/kiegroup/optaplanner-wb/pull/349

[AF-2310]: Removed deprecated samples project and changes in import projects

---

jbpm-wb-integration/jbpm-wb-integration-backend/src/test/java/org/jbpm/workbench/wi/backend/server/workitem/ServiceTaskServiceImplTest.java

JBPM-8947 Service Task related tests failing due to WIH exact count assertion

---

jbpm-wb-showcase/pom.xml
jbpm-wb-showcase/src/main/resources/org/jbpm/workbench/jBPMShowcase.gwt.xml

**Task**: [AF-2366](https://issues.redhat.com/browse/AF-2366)
**Related PRs**:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1151
- https://github.com/kiegroup/kie-soup/pull/124
- https://github.com/kiegroup/appformer/pull/872
- https://github.com/kiegroup/kie-wb-common/pull/3098
- https://github.com/kiegroup/jbpm-wb/pull/1406
- https://github.com/kiegroup/drools-wb/pull/1278
- https://github.com/kiegroup/optaplanner-wb/pull/352
- https://github.com/kiegroup/kie-wb-distributions/pull/1005

[AF-2366] BC Maven Archetype Support

---

jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/items/NamedObjectItemPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/items/NamedObjectItemView.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/items/ObjectItemPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/items/ObjectItemView.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/general/DeploymentsGeneralSettingsPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/general/DeploymentsGeneralSettingsView.java
jbpm-wb-integration/jbpm-wb-integration-client/src/test/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/items/NamedObjectItemPresenterTest.java
jbpm-wb-integration/jbpm-wb-integration-client/src/test/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/items/ObjectItemPresenterTest.java
jbpm-wb-integration/jbpm-wb-integration-client/src/test/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/sections/general/DeploymentsGeneralSettingsPresenterTest.java

* Changed KieEnumSelectElement implementations to be used as Element
* Fixed Tests
Ensemble:
kie-wb-common [#3105](https://github.com/kiegroup/kie-wb-common/pull/3105)
Deployable WAR link: https://drive.google.com/open?id=11j9krqVd5xgBhoGw_sMBxAkGICkbzYTj

AF-2404 : Package dropdown button is not visible (slowly appears) when creating an asset

---

jbpm-wb-showcase/pom.xml

**Task**: [AF-2363](https://issues.redhat.com/browse/AF-2363)
**Related PRs**:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1171
- https://github.com/kiegroup/appformer/pull/881
- https://github.com/kiegroup/kie-wb-common/pull/3126
- https://github.com/kiegroup/drools-wb/pull/1293
- https://github.com/kiegroup/optaplanner-wb/pull/353
- https://github.com/kiegroup/jbpm-wb/pull/1410
- https://github.com/kiegroup/kie-wb-distributions/pull/1009

[AF-2363] Be able to create projects from empty repositories

---

jbpm-wb-showcase/pom.xml

Adding misssing deps to showcase
@cristianonicolai would you mind take a look?
https://github.com/kiegroup/kogito-tooling/pull/66
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1195
https://github.com/kiegroup/appformer/pull/894
https://github.com/kiegroup/kie-wb-common/pull/3156
https://github.com/kiegroup/jbpm-wb/pull/1414
https://github.com/kiegroup/drools-wb/pull/1310
https://github.com/kiegroup/kie-wb-distributions/pull/1013

KOGITO-879 KOGITO-880 KOGITO-881: State Control API (undo/redo)

---

jbpm-wb-integration/jbpm-wb-integration-backend/pom.xml
jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/workitem/RepositoryStorageVFSImpl.java

Part of https://github.com/kiegroup/kie-soup/pull/137

KOGITO-1546 XStreamUtils kie-soup refactoring

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/README.md
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/src/main/assembly/assembly-eap-7.xml
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/src/main/assembly/assembly-wildfly.xml
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/src/main/assembly/component-wildfly-eap-7-common.xml
jbpm-wb-integration/jbpm-wb-integration-backend/src/main/resources/casemgmt.properties

https://issues.redhat.com/browse/JBPM-9044
Parent PR kiegroup/droolsjbpm-build-bootstrap/pull/1203

JBPM-9044: upgrade to WF18

---

jbpm-wb-showcase/src/main/java/org/jbpm/workbench/client/home/HomeProducer.java

Related to:
* https://github.com/kiegroup/appformer/pull/895
* https://github.com/kiegroup/kie-wb-common/pull/3314
* https://github.com/kiegroup/drools-wb/pull/1379
* https://github.com/kiegroup/jbpm-wb/pull/1436
* https://github.com/kiegroup/optaplanner-wb/pull/371
* https://github.com/kiegroup/kie-wb-distributions/pull/1010

AF-2411: Added HomeProducer initializer

---

jbpm-wb-kie-server/jbpm-wb-kie-server-api/pom.xml
jbpm-wb-showcase/pom.xml

parent PR kiegroup/droolsjbpm-build-bootstrap/pull/1345

fixing Enforcer error after keycloak upgrade

---

jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/PerspectiveIds.java
jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/errorlist/ExecutionErrorListPresenterTest.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/pom.xml
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/definition/list/ProcessDefinitionListPresenter.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/definition/list/ProcessDefinitionListPresenterTest.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListPresenterTest.java
jbpm-wb-showcase/src/main/java/org/jbpm/workbench/client/ShowcaseEntryPoint.java
jbpm-wb-showcase/src/main/java/org/jbpm/workbench/client/home/HomeProducer.java

Refactoring imports based on PR kiegroup/kie-wb-common#3315
Related PR's : 
https://github.com/kiegroup/appformer/pull/976
https://github.com/kiegroup/kie-wb-common/pull/3315 
https://github.com/kiegroup/kie-wb-distributions/pull/1033
https://github.com/kiegroup/drools-wb/pull/1378
https://github.com/kiegroup/jbpm-wb/pull/1435
https://github.com/kiegroup/optaplanner-wb/pull/370

BAPL-1547 :Improvement the REST API in Business-Central adding the groups/roles operations available in the UI

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml
jbpm-wb-showcase/pom.xml

https://issues.redhat.com/browse/JBPM-9189
parent PR kiegroup/droolsjbpm-build-bootstrap#1364

JBPM-9189: fixing versions for new Errai Wildfly distribution 19.1.0.SP1

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/src/main/assembly/assembly-wildfly.xml
jbpm-wb-integration/jbpm-wb-integration-backend/src/main/resources/casemgmt.properties

https://issues.redhat.com/browse/JBPM-9201
related PR: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1371

JBPM-9201: fixed deployable classifier to wildfly19

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/src/main/assembly/assembly-wildfly.xml
jbpm-wb-integration/jbpm-wb-integration-backend/src/main/resources/casemgmt.properties

(cherry picked from commit 9103d0668c393bb10f6750023fdb514fb32f3c2c)
[link](https://www.example.com)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1437
* https://github.com/kiegroup/jbpm/pull/1728
* https://github.com/kiegroup/droolsjbpm-integration/pull/2195
* https://github.com/kiegroup/jbpm-wb/pull/1453
* https://github.com/kiegroup/kie-wb-distributions/pull/1051
**How to retest or run**:
* a pull request please add comment: regex **[.\*[j|J]enkins,?.\*(retest|test) this.\*]**
* a full downstream build please add comment: regex …

JBPM-9201: fixed classifier for wildfly 19 (#1442)

---

jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/main/java/org/jbpm/workbench/pr/backend/server/RemoteProcessRuntimeDataServiceImpl.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/details/ProcessInstanceDetailsTabPresenter.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/instance/details/ProcessInstanceDetailsTabPresenterTest.java

Revert "JBPM-9286 UI error when parent process instance details have been rem…"

---

jbpm-wb-integration/jbpm-wb-integration-backend/pom.xml

https://issues.redhat.com/browse/BXMSPROD-685
Parent  PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1320

BXSMPROD-685: upgrade of weld to 3.x

---

jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/pom.xml
jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/main/java/org/jbpm/workbench/pr/backend/server/function/ProcessSVGFunction.java
jbpm-wb-showcase/pom.xml

**JIRA**:
[AF-2637](https://issues.redhat.com/browse/AF-2637)
This is a PR to allow custom components to retrieve SVG from Kie Server.  See https://github.com/kiegroup/appformer/pull/1067 for more information.
Merge with: https://github.com/kiegroup/appformer/pull/1067

AF-2637: Implement SVG backend Service for Kie Server

---

jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/main/java/org/jbpm/workbench/pr/backend/server/function/ProcessSVGFunction.java

[AF-2707](https://issues.redhat.com/browse/AF-2707)
Fixes the SVG function.

AF-2707: Fix SVG Function in jbpm-wb

---

jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/workitem/ServiceTaskUploadFormPresenter.java
jbpm-wb-integration/jbpm-wb-integration-client/src/test/java/org/jbpm/workbench/wi/client/workitem/ServiceTaskUploadFormPresenterTest.java

[link](https://www.example.com)
* link 2
* link 3 etc.
<pre>
How to retest a PR or trigger a specific build:
</pre>

JBPM-9313 Typo in status messsage on service task upload page

---

jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/resources/default-query-definitions.json

Modifying query as per JIRA description.
**JIRA**: 
[https://issues.redhat.com/browse/JBPM-9099](https://issues.redhat.com/browse/JBPM-9099)
** referenced prs**
https://github.com/kiegroup/kie-soup/pull/168

[JBPM-9099] Long running query at kie-server startup

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/src/test/java/org/jbpm/workbench/cm/backend/server/RemoteCaseManagementServiceImplTest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/actions/ActionsPresenterTest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/comments/CaseCommentsPresenterTest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/details/CaseDetailsPresenterTest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/milestones/CaseMilestonesPresenterTest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/newcase/NewCaseInstancePresenterTest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/overview/CaseOverviewPresenterTest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/roles/CaseRolesPresenterTest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/stages/CaseStagesPresenterTest.java
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/util/CaseRolesValidationsTest.java
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/test/java/org/jbpm/dashboard/dataset/editor/impl/RemoteDataSetDefAttributesEditorTest.java
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/test/java/org/jbpm/dashboard/renderer/client/ProcessDashboardTest.java
jbpm-wb-dashboard/jbpm-wb-dashboard-client/src/test/java/org/jbpm/dashboard/renderer/client/TaskDashboardTest.java
jbpm-wb-executor-service/jbpm-wb-executor-service-backend/src/test/java/org/jbpm/workbench/es/backend/server/RemoteExecutorServiceImplTest.java
jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormProvidingEngineTest.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/test/java/org/jbpm/workbench/ht/client/editors/taskcomments/TaskCommentsPresenterTest.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/test/java/org/jbpm/workbench/ht/client/editors/tasklogs/TaskLogItemViewTest.java
jbpm-wb-integration/jbpm-wb-integration-backend/pom.xml
jbpm-wb-integration/jbpm-wb-integration-backend/src/test/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseProjectServiceImplTest.java
jbpm-wb-integration/jbpm-wb-integration-backend/src/test/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseProvisioningServiceImplTest.java
jbpm-wb-integration/jbpm-wb-integration-backend/src/test/java/org/jbpm/workbench/wi/backend/server/dd/DDConfigUpdaterTest.java
jbpm-wb-integration/jbpm-wb-integration-client/src/test/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/DeploymentsSectionPresenterTest.java
jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/test/java/org/jbpm/workbench/ks/integration/KieServerDataSetProviderTest.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/instance/diagram/ProcessInstanceDiagramPresenterTest.java
jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/instance/log/ProcessInstanceLogItemViewTest.java

**Upgrade JDK 11 + GWT 2.9**
Feel free to comment and/or raise any concerns.
This PR continues the work done in 
- https://github.com/kiegroup/appformer/pull/1030
- https://github.com/kiegroup/appformer/pull/1039
Thanks guys for that!
**JIRA**:
[AF-1799](https://issues.redhat.com/browse/AF-1799)
**Parent Pull Request**:
- https://github.com/kiegroup/lienzo-core/pull/134
<details>
<summary>
</summary>
* <b>an upstream …

AF-1799: Upgrade JDK 11 + GWT 2.9

---

jbpm-wb-showcase/pom.xml
jbpm-wb-showcase/src/main/resources/org/jbpm/workbench/jBPMShowcase.gwt.xml

See https://issues.redhat.com/browse/KOGITO-3891
It **DEPENDS ON**:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1537
- https://github.com/kiegroup/kie-wb-common/pull/3498
Thanks!

KOGITO-3891: Stunner - Editors refactoring

---

jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/resources/default-query-definitions.json
jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/test/java/org/jbpm/workbench/ks/integration/KieServerQueryDefinitionLoaderTest.java

Jira : https://issues.redhat.com/browse/JBPM-9777

[JBPM-9777] Enrich information of jbpmHumanTasksWithAdmin default query

---

jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/test/java/org/jbpm/workbench/ks/integration/KieServerQueryDefinitionLoaderTest.java

JIRA : [JBPM-9777](https://issues.redhat.com/browse/JBPM-9777)

[JBPM-9777] Add unit test for jbpmHumanTasksWithAdminExtended query

---

jbpm-wb-showcase/pom.xml

Part of the ensemble:
**Referenced Pull Requests**:
* https://github.com/kiegroup/kie-wb-common/pull/3682
* https://github.com/kiegroup/jbpm-wb/pull/1513
* https://github.com/kiegroup/kie-wb-distributions/pull/1127
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1766
<details>
<summary>
</summary>
</details>

JBPM-9896 - Enforcer issues fix

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml
jbpm-wb-showcase/pom.xml

[https://issues.redhat.com/browse/JBPM-9899](JBPM-9899)
* link 2
* link 3 etc.
<details>
<summary>
</summary> …

JBPM-9899 JBPM WB IT tests fails

---

jbpm-wb-showcase/pom.xml

**JIRA**: 
https://issues.redhat.com/browse/AF-2884
- https://github.com/kiegroup/jbpm-wb/pull/1522
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1779
Backported from https://github.com/kiegroup/jbpm-wb/pull/1521
<details>
<summary>
</summary>
* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
* …

[7.59.x][AF-2884] upgrading opencmis version to 0.14.0

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml
jbpm-wb-showcase/pom.xml

**JIRA**: 
[AF-2880](https://issues.redhat.com/browse/AF-2880)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1776
* https://github.com/kiegroup/kie-soup/pull/231
* https://github.com/kiegroup/appformer/pull/1199
* https://github.com/kiegroup/droolsjbpm-integration/pull/2611
* https://github.com/kiegroup/jbpm-wb/pull/1518
* https://github.com/kiegroup/kie-wb-distributions/pull/1132
<details>
<summary>
</summary>
* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product …

[7.59.x] AF-2880 : Support Elytron in Business Central 

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/src/main/config/jbpm-custom.cli
jbpm-wb-showcase/src/main/config/jbpm-custom.cli

https://issues.redhat.com/browse/JBPM-9927

JBPM-9927 Skip adding KieRealm if already configured in Wildfly

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml
jbpm-wb-showcase/pom.xml

https://issues.redhat.com/browse/JBPM-10035

JBPM-10035 Skip unnecessary maven steps if tests are disabled

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml
jbpm-wb-showcase/pom.xml

Cherry-pick https://github.com/kiegroup/jbpm-wb/pull/1540

[7.67.x] JBPM-10035 Skip unnecessary maven steps if tests are disabled (#1540)

---

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml
jbpm-wb-showcase/pom.xml

**JIRA**: https://issues.redhat.com/browse/DROOLS-6853
Related PRs:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1912
https://github.com/kiegroup/drools/pull/4261
https://github.com/kiegroup/jbpm/pull/2122
https://github.com/kiegroup/droolsjbpm-integration/pull/2736
https://github.com/kiegroup/drools-wb/pull/1541
https://github.com/kiegroup/jbpm-designer/pull/929
https://github.com/kiegroup/jbpm-wb/pull/1546
https://github.com/kiegroup/kie-wb-distributions/pull/1158

[DROOLS-6853] jdk17 compatibility

---

jbpm-wb-showcase/pom.xml

**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4387
**Referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1987
* https://github.com/kiegroup/kie-wb-common/pull/3742
* https://github.com/kiegroup/drools-wb/pull/1543
* https://github.com/kiegroup/jbpm-wb/pull/1550
* https://github.com/kiegroup/kie-wb-distributions/pull/1169
**Business Central**: [WAR file](https://donwnload.here/something)
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to …

RHPAM-4387 xml-apis:xml-apis excluded

---

jbpm-wb-showcase/pom.xml

**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4387
**Referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2012
* https://github.com/kiegroup/kie-wb-common/pull/3745
* https://github.com/kiegroup/drools-wb/pull/1545
* https://github.com/kiegroup/jbpm-wb/pull/1553
* https://github.com/kiegroup/kie-wb-distributions/pull/1172
* https://github.com/kiegroup/lienzo-tests/pull/138
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use …

[BLUE] RHPAM-4387 xml-apis:xml-apis excluded

---

jbpm-wb-showcase/pom.xml

**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4387
**Referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2011
* https://github.com/kiegroup/kie-wb-common/pull/3744
* https://github.com/kiegroup/drools-wb/pull/1544
* https://github.com/kiegroup/jbpm-wb/pull/1552
* https://github.com/kiegroup/kie-wb-distributions/pull/1171
* https://github.com/kiegroup/lienzo-tests/pull/137
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use …

[7.67.x] RHPAM-4387 xml-apis:xml-apis excluded

---

jbpm-wb-integration/jbpm-wb-integration-backend/pom.xml
jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/dd/DDConfigUpdater.java
jbpm-wb-integration/jbpm-wb-integration-backend/src/test/java/org/jbpm/workbench/wi/backend/server/dd/DDConfigUpdaterTest.java
jbpm-wb-showcase/pom.xml
jbpm-wb-showcase/src/main/resources/org/jbpm/workbench/jBPMShowcase.gwt.xml
jbpm-wb-showcase/src/main/webapp/WEB-INF/web.xml

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2058
* https://github.com/kiegroup/jbpm-wb/pull/1562
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in …

[7.67.x] jbpm-designer dependecies removal

---

jbpm-wb-integration/jbpm-wb-integration-backend/pom.xml
jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/dd/DDConfigUpdater.java
jbpm-wb-integration/jbpm-wb-integration-backend/src/test/java/org/jbpm/workbench/wi/backend/server/dd/DDConfigUpdaterTest.java
jbpm-wb-showcase/pom.xml
jbpm-wb-showcase/src/main/resources/org/jbpm/workbench/jBPMShowcase.gwt.xml
jbpm-wb-showcase/src/main/webapp/WEB-INF/web.xml

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2060
* https://github.com/kiegroup/jbpm-wb/pull/1563
Cherry picked from:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2058
* https://github.com/kiegroup/jbpm-wb/pull/1562
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository. …

jbpm-designer dependecies removal

---

jbpm-wb-integration/jbpm-wb-integration-backend/pom.xml
jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/dd/DDConfigUpdater.java
jbpm-wb-integration/jbpm-wb-integration-backend/src/test/java/org/jbpm/workbench/wi/backend/server/dd/DDConfigUpdaterTest.java
jbpm-wb-showcase/pom.xml
jbpm-wb-showcase/src/main/resources/org/jbpm/workbench/jBPMShowcase.gwt.xml
jbpm-wb-showcase/src/main/webapp/WEB-INF/web.xml

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2061
* https://github.com/kiegroup/jbpm-wb/pull/1564
Cherry picked from:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2058
* https://github.com/kiegroup/jbpm-wb/pull/1562
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository. …

[7.67.x-blue] jbpm-designer dependecies removal (#1562)

---

jbpm-wb-showcase/pom.xml

**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4455
* https://github.com/kiegroup/jbpm-wb/pull/1565
* https://github.com/kiegroup/jbpm-wb/pull/1566
* https://github.com/kiegroup/jbpm-wb/pull/1567
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we …

[7.67.x][RHPAM-4455] xml-api exclusion removed. JDK8 compatible

---

jbpm-wb-showcase/pom.xml

**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4455
* https://github.com/kiegroup/jbpm-wb/pull/1565
* https://github.com/kiegroup/jbpm-wb/pull/1566
* https://github.com/kiegroup/jbpm-wb/pull/1567
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we …

[7.67.x-blue] [RHPAM-4455] xml-api exclusion removed. JDK8 compatible

---

jbpm-wb-showcase/pom.xml

**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4455
* https://github.com/kiegroup/jbpm-wb/pull/1565
* https://github.com/kiegroup/jbpm-wb/pull/1566
* https://github.com/kiegroup/jbpm-wb/pull/1567
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we …

[RHPAM-4455] xml-api exclusion removed. JDK8 compatible

---

jbpm-wb-showcase/pom.xml

This reverts commit ebbf150314e91099fb2623f085ab4aa49833f962.
**JIRA**:https://issues.redhat.com/browse/RHPAM-4455
* https://github.com/kiegroup/kie-wb-common/pull/3772
* https://github.com/kiegroup/jbpm-wb/pull/1568
* https://github.com/kiegroup/drools-wb/pull/1553
* https://github.com/kiegroup/kie-wb-distributions/pull/1188
* https://github.com/kiegroup/jbpm-wb/pull/1567
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several …

Revert "RHPAM-4387 xml-apis:xml-apis excluded (#1550)"

---

jbpm-wb-showcase/pom.xml

https://issues.redhat.com/browse/BXMSPROD-1845
Related PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2168
* https://github.com/kiegroup/kie-soup/pull/260
* https://github.com/kiegroup/appformer/pull/1368
* https://github.com/kiegroup/kie-wb-common/pull/3793
* https://github.com/kiegroup/drools-wb/pull/1562
* https://github.com/kiegroup/jbpm-wb/pull/1579
* https://github.com/kiegroup/optaplanner-wb/pull/421
* https://github.com/kiegroup/kie-wb-distributions/pull/1209
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method …

[7.67.x] [BXMSPROD-1845] elasticsearch removed from appformer (#1572)

---

jbpm-wb-showcase/pom.xml

**JIRA**: Back port for
https://issues.redhat.com/browse/BXMSPROD-1845
Related PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2169
* https://github.com/kiegroup/kie-soup/pull/261
* https://github.com/kiegroup/appformer/pull/1369
* https://github.com/kiegroup/kie-wb-common/pull/3794
* https://github.com/kiegroup/drools-wb/pull/1563
* https://github.com/kiegroup/jbpm-wb/pull/1580
* https://github.com/kiegroup/kie-wb-distributions/pull/1210
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those …

[7.67.x-blue] [BXMSPROD-1845] elasticsearch removed from appformer (#1572)

---

jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskslist/AbstractTaskListPresenter.java
jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/test/java/org/jbpm/workbench/ht/client/editors/taskslist/AbstractTaskListPresenterTest.java

[https://issues.redhat.com/browse/JBPM-10151](https://issues.redhat.com/browse/JBPM-10151)
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we …

[JBPM-10151]Tasks listed twice once completed in Business Central
