jbpm-console-ng-documents/jbpm-console-ng-documents-client/src/main/java/org/jbpm/console/ng/dm/client/document/CMISconfig/CMISConfigurationPresenter.java, jbpm-console-ng-documents/jbpm-console-ng-documents-client/src/main/java/org/jbpm/console/ng/dm/client/document/details/DocumentDetailsPresenter.java, jbpm-console-ng-human-tasks-admin/jbpm-console-ng-human-tasks-admin-client/src/main/java/org/jbpm/console/ng/ht/admin/client/editors/settings/TaskAdminSettingsPresenter.java, jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskadmin/TaskAdminPresenter.java, jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskdetails/TaskDetailsPresenter.java, jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/tasklogs/TaskLogsPresenter.java, jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskslist/grid/AbstractTasksListGridPresenter.java, jbpm-console-ng-process-runtime-admin/jbpm-console-ng-process-runtime-admin-client/src/main/java/org/jbpm/console/ng/pr/admin/client/editors/settings/ProcessAdminSettingsPresenter.java, jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/main/java/org/jbpm/console/ng/pr/client/editors/definition/details/advance/AdvancedViewProcessDefDetailsPresenter.java, jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/main/java/org/jbpm/console/ng/pr/client/editors/definition/details/basic/BasicProcessDefDetailsPresenter.java, jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/main/java/org/jbpm/console/ng/pr/client/editors/instance/details/ProcessInstanceDetailsPresenter.java, jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/main/java/org/jbpm/console/ng/pr/client/editors/instance/details/multi/ProcessInstanceDetailsMultiPresenter.java, jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/main/java/org/jbpm/console/ng/pr/client/editors/instance/list/variables/dash/DataSetProcessInstanceWithVariablesListPresenter.java, jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/main/java/org/jbpm/console/ng/pr/client/editors/instance/log/RuntimeLogPresenter.java, jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/main/java/org/jbpm/console/ng/pr/client/editors/instance/signal/ProcessInstanceSignalPresenter.java
Replace repeated occurrences of the following
new ErrorCallback<Message>() {
@Override
public boolean error( Message message, Throwable throwable ) {
ErrorPopup.showMessage( constants.UnexpectedError(throwable.getMessage()) );
return true;
}
}
with 'DefaultErrorCallback' from Uberfire extensions which does the same, but with possibly improved error messages.
I limited the scope of code reformatting only to methods containing UF Caller calls, with the exception of the first 2 files - i reformatted these as a whole (in the beginning of PR).
Also removed unused/ commented-out methods from the first 2 files.
@cristianonicolai Could you please review?
=> Use DefaultErrorCallback where possible

jbpm-console-ng-rest/pom.xml, jbpm-console-ng-rest/src/main/java/org/jbpm/console/ng/rest/ProcessImageResourceImpl.java
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/226
https://github.com/droolsjbpm/drools/pull/815
https://github.com/droolsjbpm/optaplanner/pull/200
https://github.com/droolsjbpm/jbpm/pull/487
https://github.com/droolsjbpm/droolsjbpm-integration/pull/509
https://github.com/droolsjbpm/kie-uberfire-extensions/pull/29
https://github.com/droolsjbpm/guvnor/pull/328
https://github.com/droolsjbpm/drools-wb/pull/209
https://github.com/droolsjbpm/jbpm-designer/pull/302
https://github.com/droolsjbpm/jbpm-console-ng/pull/432
https://github.com/droolsjbpm/kie-wb-distributions/pull/303
=> [DROOLS-1216] exclude commons-logging and use jcl-over-slf4j instead

jbpm-console-ng-workbench-integration/jbpm-console-ng-workbench-integration-client/src/main/java/org/jbpm/console/ng/wi/client/editors/deployment/descriptor/DeploymentDescriptorEditorPresenter.java
This PR updates the usage of PopUps in order to call the new PopUps API (that implements the MVP pattern using Errai UI).
See:
- https://issues.jboss.org/browse/GUVNOR-2431
- https://github.com/uberfire/uberfire/pull/443
=> GUVNOR-2431: Redesign Copy, Save, Rename, Restore and Delete Popups (away from FormStylePopup)

jbpm-console-ng-rest/src/main/java/org/jbpm/console/ng/rest/ProcessImageResourceImpl.java, jbpm-console-ng-rest/src/test/java/org/jbpm/console/ng/rest/ProcessImageResourceTest.java
(cherry picked from commit fe30eaa9c00f9bde95db5430636abc0910cb943f)
same here, @mrietveld do you mind taking a look?
=> RHBPMS-4117 - jBPM UI - all passed nodes are marked as active

jbpm-console-ng-workbench-integration/jbpm-console-ng-workbench-integration-backend/src/main/java/org/jbpm/console/ng/wi/backend/server/dd/DDConfigUpdater.java, jbpm-console-ng-workbench-integration/jbpm-console-ng-workbench-integration-backend/src/test/java/org/jbpm/console/ng/wi/backend/server/dd/DDConfigUpdaterTest.java, jbpm-console-ng-workbench-integration/jbpm-console-ng-workbench-integration-backend/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider
Note - DEPENDS ON DESIGNER PR 
https://github.com/droolsjbpm/jbpm-designer/pull/377
(please have jenkins retest this pr once the depends one has been added)
Allow to install workitem information into the deployment descriptor. This is needed for the automatic installation of workitems into the DD for BPMSPL-295.
=> BPMSPL-295 - Higher level of automation when importing custom workItemHandlers from a service repository

jbpm-console-ng-dashboard/jbpm-console-ng-dashboard-client/src/main/java/org/jbpm/dashboard/renderer/client/panel/TaskDashboard.java, jbpm-console-ng-documents/jbpm-console-ng-documents-client/src/main/java/org/jbpm/console/ng/dm/client/document/CMISconfig/CMISConfigurationPresenter.java, jbpm-console-ng-documents/jbpm-console-ng-documents-client/src/main/java/org/jbpm/console/ng/dm/client/document/details/DocumentDetailsPresenter.java, jbpm-console-ng-generic/jbpm-console-ng-generic-client/src/main/java/org/jbpm/console/ng/gc/client/menu/ServerTemplateSelectorMenuBuilder.java, jbpm-console-ng-human-tasks-admin/jbpm-console-ng-human-tasks-admin-client/src/main/java/org/jbpm/console/ng/ht/admin/client/editors/settings/TaskAdminSettingsPresenter.java, jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskadmin/TaskAdminPresenter.java, jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskassignments/TaskAssignmentsPresenter.java, jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskcomments/TaskCommentsPresenter.java, jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskdetails/TaskDetailsPresenter.java, jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/tasklogs/TaskLogsPresenter.java, jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskprocesscontext/TaskProcessContextPresenter.java, jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskslist/grid/AbstractTasksListGridPresenter.java, jbpm-console-ng-process-runtime-admin/jbpm-console-ng-process-runtime-admin-client/src/main/java/org/jbpm/console/ng/pr/admin/client/editors/settings/ProcessAdminSettingsPresenter.java, jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/main/java/org/jbpm/console/ng/pr/client/editors/definition/details/advance/AdvancedViewProcessDefDetailsPresenter.java, jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/main/java/org/jbpm/console/ng/pr/client/editors/definition/details/basic/BasicProcessDefDetailsPresenter.java, jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/main/java/org/jbpm/console/ng/pr/client/editors/instance/details/ProcessInstanceDetailsPresenter.java, jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/main/java/org/jbpm/console/ng/pr/client/editors/instance/details/multi/ProcessInstanceDetailsMultiPresenter.java, jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/main/java/org/jbpm/console/ng/pr/client/editors/instance/list/variables/dash/DataSetProcessInstanceWithVariablesListPresenter.java, jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/main/java/org/jbpm/console/ng/pr/client/editors/instance/log/RuntimeLogPresenter.java, jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/main/java/org/jbpm/console/ng/pr/client/editors/instance/signal/ProcessInstanceSignalPresenter.java, jbpm-console-ng-workbench-integration/jbpm-console-ng-workbench-integration-client/src/main/java/org/jbpm/console/ng/wi/client/editors/deployment/descriptor/DeploymentDescriptorEditorPresenter.java
There's now single uncaught exception handler that removes the need to define empty DefaultErrorCallback on callers https://github.com/droolsjbpm/kie-wb-common/blob/master/kie-wb-common-screens/kie-wb-common-workbench/kie-wb-common-workbench-client/src/main/java/org/kie/workbench/common/workbench/client/entrypoint/DefaultWorkbenchEntryPoint.java
=> GUVNOR-2673 Default ExceptionHandler that pops up any uncaught RuntimeException

jbpm-console-ng-executor-service/jbpm-console-ng-executor-service-client/src/main/java/org/jbpm/console/ng/es/client/editors/requestlist/RequestListViewImpl.java, jbpm-console-ng-executor-service/jbpm-console-ng-executor-service-client/src/test/java/org/jbpm/console/ng/es/client/editors/requestlist/RequestListViewTest.java, jbpm-console-ng-generic/jbpm-console-ng-generic-client/src/main/java/org/jbpm/console/ng/gc/client/list/base/AbstractMultiGridView.java, jbpm-console-ng-generic/jbpm-console-ng-generic-client/src/test/java/org/jbpm/console/ng/gc/client/list/base/AbstractMultiGridViewTest.java, jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskslist/grid/TasksListGridViewImpl.java, jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskslist/grid/dash/DataSetTasksListGridViewImpl.java, jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/test/java/org/jbpm/console/ng/ht/client/editors/taskslist/grid/dash/DataSetTasksListGridViewTest.java, jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/main/java/org/jbpm/console/ng/pr/client/editors/instance/list/dash/DataSetProcessInstanceListViewImpl.java, jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/main/java/org/jbpm/console/ng/pr/client/editors/instance/list/variables/dash/DataSetProcessInstanceListVariableViewImpl.java, jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/main/java/org/jbpm/console/ng/pr/client/editors/instance/list/variables/dash/DataSetProcessInstanceWithVariablesListViewImpl.java, jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/test/java/org/jbpm/console/ng/pr/client/editors/instance/list/dash/DataSetProcessInstanceListViewTest.java, jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/test/java/org/jbpm/console/ng/pr/client/editors/instance/list/variables/dash/DataSetProcessInstanceWithVariablesListViewTest.java
Force to set the first tab at the end of restoring filter to avoid show results of other queries in tabs selected while restoring is being done.
=> RHBPMS-4246: Jobs: Queued tab displays jobs in status DONE

jbpm-console-ng-business-domain/jbpm-console-ng-business-domain-backend/pom.xml, jbpm-console-ng-business-domain/jbpm-console-ng-business-domain-backend/src/main/java/org/jbpm/console/ng/bd/integration/KieServerDataSetManager.java, jbpm-console-ng-business-domain/jbpm-console-ng-business-domain-backend/src/main/java/org/jbpm/console/ng/bd/integration/KieServerDataSetProvider.java, jbpm-console-ng-business-domain/jbpm-console-ng-business-domain-backend/src/test/java/org/jbpm/console/ng/bd/integration/KieServerDataSetManagerTest.java
@mswiderski we need this one as well :)
I am wondering though if console-ng should depend on this artifact? I know its used to catch the particular exception, but I am wondering if it we should be it using here, since the exception seems low level?
=> [JBPM-5366] replace kie-remote-common with kie-server-common

jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-showcase/pom.xml, jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-showcase/src/main/java/org/jbpm/console/ng/cm/server/JGitFileSystemProvider.java, jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-showcase/src/main/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider, jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-showcase/src/test/java/org/jbpm/console/ng/cm/server/JGitFileSystemProviderTest.java
Avoid conflict with workbench running in the same server/host.
=> Disable ssh and git daemon by default

jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/comments/CaseCommentsPresenter.java, jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/details/CaseDetailsPresenter.java, jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/overview/CaseOverviewPresenter.java, jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/roles/CaseRolesPresenter.java, jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/util/AbstractCaseInstancePresenter.java, jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/test/java/org/jbpm/console/ng/cm/client/roles/CaseRolesPresenterTest.java
Take advantage of existing AbstractPresenter class to initialize connection between view and presenter.
The change required making `AbstractCaseInstancePresenter` extend the generic `AbstractPresenter` and renaming the `viewXYZ` fields in the subclasses to `view` so it is inherited from `AbstractPresenter`. 
Also removed some duplicated TranslationService fields in the subclasses which are alreade declared as protected in `AbstractCaseInstancePresenter`.
UPDATE: also removed `@PostConstruct` methods for initializing view which are no longer necessary.
=> Reuse AbstractPresenter in Case*Presenters

jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/roles/CaseRoleItemView.css, jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/roles/CaseRoleItemView.html, jbpm-console-ng-case-mgmt/jbpm-console-ng-case-mgmt-client/src/main/java/org/jbpm/console/ng/cm/client/roles/CaseRoleItemView.java
Avoid overflow by positioning user/group name on top of role name instead of side by side.
=> Fix user/group name and role name positioning

jbpm-console-ng-executor-service/jbpm-console-ng-executor-service-client/src/main/java/org/jbpm/console/ng/es/client/editors/requestlist/RequestListPresenter.java, jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/main/java/org/jbpm/console/ng/ht/client/editors/taskslist/grid/AbstractTasksListGridPresenter.java, jbpm-console-ng-human-tasks/jbpm-console-ng-human-tasks-client/src/test/java/org/jbpm/console/ng/ht/client/editors/taskslist/grid/AbstractTasksListGridPresenterTest.java, jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/main/java/org/jbpm/console/ng/pr/client/editors/instance/list/variables/dash/DataSetProcessInstanceWithVariablesListPresenter.java, jbpm-console-ng-process-runtime/jbpm-console-ng-process-runtime-client/src/test/java/org/jbpm/console/ng/pr/client/editors/instance/list/variables/dash/DataSetProcessInstanceWithVariablesListPresenterTest.java
Added a check before the data is loaded in table rows to verify that the results match with the last tab  requested to avoid fill data with previous request.
=> JBPM-4246: Jobs: Queued tab displays jobs in status DONE

jbpm-wb-showcase/pom.xml, jbpm-wb-showcase/src/main/java/org/jbpm/workbench/client/perspectives/ProjectAuthoringPerspective.java, jbpm-wb-showcase/src/main/java/org/jbpm/workbench/server/impl/AppSetup.java, jbpm-wb-showcase/src/main/resources/org/jbpm/workbench/jBPMShowcase.gwt.xml
Remove repository initialization from AppSetup
The examples will be moved from https://github.com/droolsjbpm/jbpm-playground to https://github.com/droolsjbpm/kie-wb-playground. This might be a good place to discuss which examples should be included in the workbench by default.
=> PLANNER-707: Workbench "import example dialog": Embed stock example repositories

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
As JMS is not in the classpath a ClassNotFoundException: javax.jms.JMSException is thrown when creating a client connection.
=> Fix missing JMS API in the classpath when connecting to the Kie Server

jbpm-wb-forms/jbpm-wb-forms-client/pom.xml, jbpm-wb-forms/jbpm-wb-forms-client/src/main/java/org/jbpm/workbench/forms/client/display/process/QuickNewProcessInstancePopup.java, jbpm-wb-forms/jbpm-wb-forms-client/src/main/java/org/jbpm/workbench/forms/client/display/process/QuickNewProcessInstancePopup.ui.xml, jbpm-wb-forms/jbpm-wb-forms-client/src/main/resources/org/jbpm/workbench/forms/JbpmWorkbenchFormsClient.gwt.xml, jbpm-wb-process-runtime/jbpm-wb-process-runtime-api/src/main/java/org/jbpm/workbench/pr/events/ProcessDefSelectionEvent.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-api/src/main/java/org/jbpm/workbench/pr/model/ProcessSummary.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/main/java/org/jbpm/workbench/pr/backend/server/ProcessSummaryMapper.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/main/java/org/jbpm/workbench/pr/backend/server/RemoteProcessRuntimeDataServiceImpl.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/test/java/org/jbpm/workbench/pr/backend/server/ProcessSummaryMapperTest.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/test/java/org/jbpm/workbench/pr/backend/server/RemoteProcessRuntimeDataServiceImplTest.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/definition/details/BaseProcessDefDetailsPresenter.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/definition/details/BaseProcessDefDetailsViewImpl.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/definition/details/advance/AdvancedViewProcessDefDetailsPresenter.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/definition/details/basic/BasicProcessDefDetailsPresenter.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/definition/details/multi/BaseProcessDefDetailsMultiPresenter.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/definition/details/multi/BaseProcessDefDetailsMultiViewImpl.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/definition/details/multi/advance/AdvancedProcessDefDetailsMultiPresenter.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/definition/details/multi/basic/BasicProcessDefDetailsMultiPresenter.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/definition/list/ProcessDefinitionListPresenter.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/definition/list/ProcessDefinitionListViewImpl.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/definition/details/multi/BaseProcessDefDetailsMultiPresenterTest.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/definition/details/multi/advance/AdvancedProcessDefDetailsMultiPresenterTest.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/definition/details/multi/basic/BasicProcessDefDetailsMultiPresenterTest.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/definition/list/ProcessDefinitionListPresenterTest.java
Blocked start process instances from process definition list, process definition details and process instance list.
Moved mapper logic between ProcessDefinition and ProcessSummary into a single place/class.
Removed unsuded attributtes from ProcessSummary
Updated QuickNewProcessInstance to have a single dropdown with process definitions grouped by container.
Updated QuickNewProcessInstance dropdown style to match PatternFly guidelines
=> JBPM-5675 - Prevent start process instance options from case definitions

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-api/src/main/java/org/jbpm/workbench/cm/model/CaseActionSummary.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-api/src/main/java/org/jbpm/workbench/cm/util/CaseActionStatus.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/src/main/java/org/jbpm/workbench/cm/backend/server/CaseActionAdHocMapper.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/src/main/java/org/jbpm/workbench/cm/backend/server/CaseActionNodeInstanceMapper.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/src/main/java/org/jbpm/workbench/cm/backend/server/RemoteCaseManagementServiceImpl.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/src/test/java/org/jbpm/workbench/cm/backend/server/CaseActionMapperTest.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/src/test/java/org/jbpm/workbench/cm/backend/server/CaseInstanceMapperTest.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/src/test/java/org/jbpm/workbench/cm/backend/server/RemoteCaseManagementServiceImplTest.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/actions/CaseActionItemView.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/actions/CaseActionsPresenter.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/actions/NewActionViewImpl.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/actions/ActionsPresenterTest.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/src/main/java/org/jbpm/workbench/cm/server/MockCaseManagementService.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/src/main/resources/case_actions.json, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/src/main/resources/case_stages.json
Case Action type can be: 
- AD_HOC_TASK,
- DYNAMIC_USER_TASK
- DYNAMIC_SUBPROCESS_TASK
Case Action status can be:
- AVAILABLE,
- IN_PROGRESS
- COMPLETED
The idea behind status AVAILABLE is quite simple.
All dynamic actions will have status AVAILABLE throughout the entire case life-cycle. 
The same goes for ALL ad-hoc tasks regardless of their scope (case level or stage level). This treatment of ad-hoc tasks is safe because when displaying available ad-hoc actions which are part of a stage, the stage status will determine whether its ad-hoc actions will be exposed to the case worker or not (i.e. only if the stage status is Available, its ad-hoc actions will be offered).
Have also changed the mapping of Case Action "id" property in CaseActionNodeInstanceMapper, so it's mapped to Node …
=> Case Actions: Separate status from type in model

jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/menu/ServerTemplateSelectorMenuBuilder.java, jbpm-wb-common/jbpm-wb-common-client/src/test/java/org/jbpm/workbench/common/client/menu/ServerTemplateSelectorMenuBuilderTest.java
Catch KieServicesHttpException thrown when the kie-server still is not ready to execute dataset queries while it's registering dataSetDefinitions
=> JBPM-5695: Exception in Task list for restarted Kie server

jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/util/UTCTimeBoxImplShared.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/main/java/org/jbpm/workbench/pr/backend/server/RemoteProcessRuntimeDataServiceImpl.java, pom.xml
Enable findbugs-maven-plugin to fail the build when serious bug has been identified. Findbugs plugin is only executed when the build is run with `-Dfull` (which is the case in kie-jenkins CI jobs).
At the same time I'm providing fixes to 2 issues identified by the plugin.
The configuration of the plugin can be found in [droolsjbpm-build-bootstrap/pom.xml](https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/pom.xml#L1165-L1182) and has been already fine-tuned by QE to only fail the build in cases where it's almost certain there's a bug.
=> Enable findbugs.failOnViolation

jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/list/AdvancedSearchFiltersViewImpl.java
On Firefox (and probably other browser), the numeric keys didn't work. Also added detection of left and right arrow keys
=> Fixed advanced search numeric inputs on Firefox

jbpm-wb-showcase/pom.xml, jbpm-wb-showcase/src/main/resources/org/jbpm/workbench/jBPMShowcase.gwt.xml
Add the required dependencies so as to make the project dashboard metrics work in showcase.
@nmirasch  Can you verify please?
jenkins execute full downstream build
=> JBPM-5876: Fix runtime dependencies

jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/ProcessFormsValuesProcessor.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/TaskFormValuesProcessor.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormProvidingEngineTest.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormsValuesProcessorTest.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/ProcessFormsValuesProcessorTest.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/TaskFormValuesProcessorTest.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/process/AbstractStartProcessFormTest.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/task/AbstractTaskFormProvidingTest.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/util/FormContentReader.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/resources/forms/invoices-taskform.frm, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/resources/forms/modify-taskform.frm, jbpm-wb-showcase/pom.xml
This PR adapts code to API changes introduced by:
JBPM-5736: Update taskforms component menu on task/process change.
JBPM-5985: Forms are generated incorrectly after a removal of the process/task variable.
JBPM-5723: If you delete a data field, there is no response in the form connected to it.
JBPM-5911: DatePicker should be created from LocalDate, LocalDateTime and OffsetDateTime data types.
@jsoltes @cristianonicolai   could you take a look?
Relates to:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/465
https://github.com/kiegroup/kie-wb-common/pull/946
https://github.com/kiegroup/jbpm-designer/pull/633
https://github.com/kiegroup/jbpm-wb/pull/778
https://github.com/kiegroup/kie-wb-distributions/pull/543
=> JBPM-5736, JBPM-5985, JBPM-5723 & JBPM-5911 Form synchronization when model changes

jbpm-wb-integration/jbpm-wb-integration-backend/pom.xml
GUVNOR-3023: Support provisioning of KIE Server instances by Guvnor ALA
https://issues.jboss.org/browse/GUVNOR-3023
This was cherry-picked from the work on the 7.2.x branch, and rebased against master.
=> GUVNOR-3023: Support provisioning of KIE Server instances by Guvnor ALA

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml, jbpm-wb-showcase/pom.xml
Move most backend dependencies to runtime scope, removing it from the GWT compiler classpath
=> JBPM-6376 - Review GWT compiler classpath

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml, jbpm-wb-showcase/pom.xml
Move most backend dependencies to runtime scope, removing it from the GWT compiler classpath
=> [7.3.x] JBPM-6376 - Review GWT compiler classpath

jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/signal/ProcessInstanceSignalPresenter.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/signal/ProcessInstanceSignalViewImpl.html, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/signal/ProcessInstanceSignalViewImpl.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/resources/i18n/Constants.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/resources/org/jbpm/workbench/pr/client/resources/i18n/Constants.properties, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/instance/signal/ProcessInstanceSignalPresenterTest.java
Check if the signal name is set and changed the abort confirm popup
=> [7.3.x] RHBPMS-4925: HTTP 405 when sending empty signal name to process instance

jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/ProcessFormsValuesProcessor.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/TaskFormValuesProcessor.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormProvidingEngineTest.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormsValuesProcessorTest.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/ProcessFormsValuesProcessorTest.java
Copy of https://github.com/kiegroup/jbpm-wb/pull/903
@cristianonicolai @jsoltes could you please take a look?
https://github.com/kiegroup/kie-wb-common/pull/1187
https://github.com/kiegroup/jbpm-designer/pull/666
https://github.com/kiegroup/jbpm-wb/pull/904
=> [7.3.x] JBPM-6409: In taskforms data inputs (if different than outpus) should be readonly by default. (Also fixes JBPM-5742)

jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/ProcessFormsValuesProcessor.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/TaskFormValuesProcessor.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormProvidingEngineTest.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormsValuesProcessorTest.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/ProcessFormsValuesProcessorTest.java
@cristianonicolai  @jsoltes could you please take a look?
https://github.com/kiegroup/kie-wb-common/pull/1186
https://github.com/kiegroup/jbpm-designer/pull/665
https://github.com/kiegroup/jbpm-wb/pull/903
=> [8.0.x] JBPM-6409: In taskforms data inputs (if different than outpus) should be readonly by default. (Also fixes JBPM-5742)

jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/test/java/org/jbpm/workbench/pr/backend/server/RemoteProcessRuntimeDataServiceImplTest.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/pom.xml, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/details/ProcessInstanceDetailsPresenter.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/instance/details/multi/ProcessInstanceDetailsPresenterTest.java
@cristianonicolai @nmirasch @triceo  Hi folks, these are the tests which I came up with in attempt to cover JBPM-6469 with a reproducer.
However, while writing the tests I realized that the issue is not on jBPM Workbench side, but rather on Kie Server side (```TaskSummaryList``` field doesn't get initialized in ```org.kie.server.api.model.instance.ProcessInstance```), which in turn returns ```null``` when queried in our backend and as a result an empty list is displayed in UI under ```Active user tasks``` in Process Instance Details.
Anyway, I added two tests (one for backend part and one for the client part), which would have caught this type of issue, if the issue had been on jBPM Workbench side.
I guess, the only way this issue would have been caught by tests in ```jbpm-wb```, if there …
=> [JBPM-6571] Write comminity tests to cover JBPM-6469

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml, jbpm-wb-showcase/pom.xml, pom.xml
Please see this [PR](https://github.com/kiegroup/kie-soup/pull/8) for general discussion.
=> AF-593+: Move uberfire-maven-utils to kie-soup.

jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/builder/BPMPostBuildHandler.java, jbpm-wb-integration/jbpm-wb-integration-backend/src/test/java/org/jbpm/workbench/wi/backend/server/dd/DDConfigUpdaterTest.java
Hello @mswiderski , could you please take a look as the author of the original code?
The way it was implemented was causing 3 exceptions in server log every time you click build & deploy in kie-wb for a project that doesn't have any associated kie-deployment-descriptor.xml (like evaluation example project)
<details><summary>Exceptions like this</summary>
<pre>
14:48:23,536 ERROR [org.guvnor.common.services.backend.exceptions.ExceptionUtilities] (default task-13) Exception thrown: null: org.uberfire.java.nio.file.NoSuchFileException
at org.uberfire.java.nio.fs.jgit.JGitFileSystemProvider.getFileAttributeView(JGitFileSystemProvider.java:1930)
at org.uberfire.java.nio.file.Files.getFileAttributeView(Files.java:617)
at org.uberfire.io.impl.IOServiceDotFileImpl.getFileAttributeView(IOServiceDot …
=> JBPM-6619: Prevent build errors when deployment descriptor doesn't exist

jbpm-wb-showcase/pom.xml
A new Metadata index had been added. Its intention is to have an alternative to Lucene backend so you can use it, for instance in Openshift or on premise without zookeeper/helix to replicate those assets.
The idea is to maintain the same Lucene API but to transform it to Elasticsearch compatible messages. There is no need to change any Lucene Query to make it work. There is a class called **LuceneIndexEngine** that is not **public** anymore because it was very coupled to Lucene FS implementation so now it's behind a new Interface called **IndexProvider**. It tries to generate an abstraction for indexing a querying an index engine using domain objects and not lucene documents anymore.
The default indexing engine is Lucene but you can change it with a System Property:
- …
=> [AF-549-elastic]: Added new indexing backend to add elasticsearch support

jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/jobdetails/JobDetailsPresenter.java, jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/jobdetails/JobDetailsViewImpl.java, jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/jobdetails/JobDetailsPresenterTest.java, jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListPresenterTest.java, jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/util/JobUtils.java
@cristianonicolai @nmirasch Enhanced unit tests as far as they could go, as I'm not planning to add any Selenium or integration tests in the future for Job Details.
Also, I introduced a small fix for NPE in case of clicking on a job which is still being shown in the Jobs list, but has already been deleted in the background by executor's log clean-up command (named test ```testStaleJobSelected```, but I'm open to suggestions for a maybe clearer name :))
=> [JBPM-6626] Enhance Job Details tests

jbpm-wb-showcase/pom.xml
This dependency should not be here. If it is needed it should be
declared by the module that actually needs it (e.g. the
jbpm-designer-backed).
=> Remove bogus batik-ext dependency

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/newcase/NewCaseInstancePresenter.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/newcase/NewCaseInstanceViewImpl.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/newcase/NewCaseInstancePresenterTest.java
@cristianonicolai @nmirasch Made case owner input validation more strict in order to prevent issues occurring after a new case instance is started but has an invalid case owner format.
The role cardinality validation and proper input formatting is aligned with how we handle all other case roles defined in the case definition.
The owner role is limited to only one assignment until we decide to relax that constraint in the future.
=> [JBPM-6703] Case owner input allows spaces and comma separated list of entries

jbpm-wb-showcase/pom.xml
Hey @manstis @jomarko @hasys 
It was missing this PR to make the build work again. 
Please merge at same time as:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/672
- https://github.com/kiegroup/kie-wb-common/pull/1362
- https://github.com/kiegroup/kie-wb-distributions/pull/670
Thanks!
=> JBPM-6748: Removed Stunner's BasicSet dependencies from the webapp

jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/list/AbstractScreenListPresenter.java, jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/quicknewjob/NewJobPresenter.java, jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/quicknewjob/NewJobViewImpl.java, jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListPresenter.java, jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/quicknewjob/NewJobPresenterTest.java, jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/test/java/org/jbpm/workbench/es/client/editors/requestlist/RequestListPresenterTest.java
@cristianonicolai @nmirasch Added a couple of more tests and did a small re-factoring of the existing tests.
Two bugs fixed:
1. On new job dialog re-open, the basic tab/pane is not set by default, although I could see in the code that was the intended behavior.
2.  Bogus additional job parameters entries (added via Advanced pane) i.e. those which contain _Click to Edit_ in place of parameter key/value are sent to Kie Server and as a consequence shown in _Job Details_ panel.
=> [JBPM-6783] Jobs: Test new job dialog

jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/list/ExtendedPagedTable.java
Depends on https://github.com/kiegroup/appformer/pull/202
=> JBPM-6892 - Remove spacing between table results and controls

jbpm-wb-integration/jbpm-wb-integration-backend/pom.xml, jbpm-wb-showcase/pom.xml, jbpm-wb-showcase/src/main/resources/application-roles.properties, jbpm-wb-showcase/src/main/resources/application-users.properties, jbpm-wb-showcase/src/main/resources/logback.xml, jbpm-wb-showcase/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
Repeated effort of reverted https://github.com/kiegroup/jbpm-wb/pull/976
=> Upgrade supported WildFly version to 11.

jbpm-wb-forms/jbpm-wb-forms-backend/pom.xml, jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/KieWorkbenchFormsValuesProcessor.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/ProcessFormsValuesProcessor.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/TaskFormValuesProcessor.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/FormServiceEntryPointImplTest.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormProvidingEngineTest.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormsValuesProcessorTest.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/ProcessFormsValuesProcessorTest.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/TaskFormValuesProcessorTest.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/process/AbstractStartProcessFormTest.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/task/AbstractTaskFormProvidingTest.java, jbpm-wb-showcase/pom.xml
There has been some packages changes.
@cristianonicolai could you please take a look?
https://github.com/kiegroup/kie-wb-distributions/pull/704
This PR is part of an ensemble, merge with:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/720
https://github.com/kiegroup/kie-wb-common/pull/1492
https://github.com/kiegroup/jbpm-designer/pull/754
https://github.com/kiegroup/jbpm-wb/pull/993
https://github.com/kiegroup/kie-wb-distributions/pull/704
=> BAPL-764-migration-tool: Provide migration path from old Form Modeler to the new one

jbpm-wb-showcase/pom.xml
Hey @hasys @jomarko 
This removes the use on the showcase of some unused services from Stunner. 
It **depends on** https://github.com/kiegroup/kie-wb-common/pull/1509
Thanks!
=> JBPM-5649: Removed dependency to Stunner's default backend services.

jbpm-wb-process-runtime/jbpm-wb-process-runtime-backend/src/test/java/org/jbpm/workbench/pr/backend/server/RemoteProcessServiceImplTest.java
@cristianonicolai @nmirasch Adding tests which are verifying API calls used when performing bulk actions.
With this piece added to existing presenter tests and the latest tests you @cristianonicolai added as part of the fix for bulk actions failing issue, I think we are in good shape to delete Selenium tests which are testing bulk signal/abort, with practically minimal risk.
=> [JBPM-7139] Process Instances: Add backend tests for bulk actions

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-api/src/main/java/org/jbpm/workbench/cm/model/CaseActionSummary.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/pom.xml, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-backend/src/test/java/org/jbpm/workbench/cm/backend/server/RemoteCaseManagementServiceImplTest.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/actions/CaseActionItemView.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/actions/CaseActionsListViewImpl.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/actions/CaseActionsPresenter.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/actions/CaseActionsViewImpl.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/actions/ActionsPresenterTest.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/stages/CaseStagesPresenterTest.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/util/AbstractCaseInstancePresenterTest.java
@cristianonicolai @nmirasch Added more tests around actions lists. It required a small re-factoring here and there and while at it, I aligned field access specifiers where seemed appropriate.
Please note the change in _CaseActionSummary_ ```equals``` implementation. The re-factoring I did to move some of the business logic to _CaseActionsPresenter_ reveled the problem with previous ```equals``` implementation. The ```id``` field can't be used to compare dynamic actions while being listed, as they don't have the concept of ```Id```.
=> [JBPM-7115] Case audit: Review tests

jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/tasklogs/TaskLogsViewImpl.java
The logs can Introduce characters like ' that are replaced at  SafeHtmlUtils.htmlEscape. To be displayed we need setInnerHTML instead  setTextContent
=> JBPM-7213: Tasks First Due Date update writes null to task log

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/list/CaseInstanceListSearchViewImpl.java, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/java/org/jbpm/workbench/cm/client/list/CaseInstanceListViewImpl.html, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/main/resources/org/jbpm/workbench/cm/client/resources/i18n/Constants.properties, jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-client/src/test/java/org/jbpm/workbench/cm/client/list/CaseInstanceListSearchViewTest.java
@cristianonicolai  I think the PR is not ready.
I just want to make sure my PR on right way.
Actually, I have two way for the issue.
first, it is the PR.
if we choice it, I think we need choice it's style , it is like start case button, or I will try to copy  RefreshMenuBuilder's style.
another, We can copy [code](https://github.com/Cory-jbpm/jbpm-wb/blob/0a4ffbd3045d0bd22d6f03dcbd4d46a0aaf60671/jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListPresenter.java#L387)  .
But I find , jbpm-case-mgmt don't have many gwt modeles, I can not inherit all modeles.
In the same time, I find case list page different to process instance list page.
I think, the PR miss unit test, can you give me example for it. …
=> JBPM-7313: Case List: Should have refresh option

jbpm-wb-showcase/pom.xml
Hello @cristianonicolai and @nmirasch ,
I'm introducing a new profile that will enable to skip gwt compilation of showcases in downstream-pullrequests jobs. In normal build, nothing is skipped. Only when you add -Pno-showcase to mvn command line, the showcases won't be gwt-compiled. Please let me know if you're ok with this change / if you can think of better way to achieve the skipping.
https://github.com/kiegroup/jbpm-wb/pull/1160
https://github.com/kiegroup/kie-wb-common/pull/1917
https://github.com/kiegroup/drools-wb/pull/877
https://github.com/kiegroup/appformer/pull/401
=> AF-1248: Add profile to enable skipping of gwt compilation of showcases

jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/dataset/AbstractDataSetReadyCallback.java, jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/dataset/DataSetAwareSelect.java, jbpm-wb-common/jbpm-wb-common-client/src/test/java/org/jbpm/workbench/common/client/dataset/AbstractDataSetReadyCallbackTest.java, jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/items/ParametersModal.java, jbpm-wb-integration/jbpm-wb-integration-client/src/main/java/org/jbpm/workbench/wi/client/editors/deployment/descriptor/items/ParametersModalView.java, jbpm-wb-showcase/src/main/java/org/jbpm/workbench/client/ShowcaseEntryPoint.java, jbpm-wb-showcase/src/test/java/org/jbpm/workbench/client/ShowcaseEntryPointTest.java
This is already merged in 7.7.x. Cherry-picking to master.
Related:
https://github.com/errai/errai/pull/352
https://github.com/kiegroup/appformer/pull/412
https://github.com/kiegroup/kie-wb-common/pull/1951
https://github.com/kiegroup/drools-wb/pull/883
https://github.com/kiegroup/jbpm-wb/pull/1169
https://github.com/kiegroup/optaplanner-wb/pull/290
https://github.com/kiegroup/kie-wb-distributions/pull/776
=> [master] AF-1226: Improve error handling displaying additional info to the GenericErrorPopup

jbpm-wb-showcase/pom.xml
Exclude this module which failed to build after required fabric8 k8s client lib upgrade to 4.1.1
Related PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/904
- https://github.com/kiegroup/kie-wb-common/pull/2319
- https://github.com/kiegroup/droolsjbpm-integration/pull/1670
- https://github.com/kiegroup/droolsjbpm-integration/pull/1611
=> JBPM-7834: Provide OpenShiftStartupStrategy - WB Integration

jbpm-wb-showcase/pom.xml
=> Fix springboot on JDK 11 (jax-ws-api)

jbpm-wb-forms/jbpm-wb-forms-backend/pom.xml, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/FormServiceEntryPointImplTest.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormProvidingEngineTest.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormsValuesProcessorTest.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormsValuesProcessorWithWrongTypesTest.java
Fixing broken tests due to some api changes.
@tomasdavidorg @cristianonicolai could you please take a look?
https://github.com/kiegroup/drools/pull/2277
https://github.com/kiegroup/kie-wb-common/pull/2525
https://github.com/kiegroup/jbpm-wb/pull/1316
https://github.com/kiegroup/jbpm-designer/pull/842
https://github.com/kiegroup/kie-wb-distributions/pull/898
=> JBPM-6848: Form Generation fails generating forms for classes on external dependencies

jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/main/java/org/jbpm/workbench/pr/client/editors/diagram/ProcessDiagramWidgetViewImpl.java, jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/diagram/ProcessDiagramWidgetViewTest.java
work with svg viewBox attribute instead with and height
=> JBPM-8306: Process diagram images are hardcoded to large sizes

jbpm-wb-showcase/pom.xml
Adding uberfire-preference-client-backend dependency, which is introduced by: kiegroup/appformer#724
MERGE WITH kiegroup/appformer#724
=> AF-1987: Adding uberfire-preference-client-backend dep

jbpm-wb-kie-server/jbpm-wb-kie-server-api/src/main/java/org/jbpm/workbench/ks/utils/KieServerUtils.java
Business Central, as controller, tries to load keycloak classes. If Keycloak classes are not available, then it loads the default credentials provider to communicate with Kie Server registered servers.
After `AF-2086`, keycloak JARs are available by default in Business Central, which means that BC will tries to use Keycloak, even if user did not setup keycloak, leading to errors and a complete failure of BC components that requires Kie Server access (dashboards, servers management...)
This PR aims to create a new system property which allow users to disable Keycloak classes loading. Only if the system property `org.jbpm.workbench.kie_server.keycloak` is set to true BC will try to load keycloak classes.
=> JBPM-8763: Tries to load KeyCloak if a flag is true

jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/list/AbstractMultiGridPresenter.java, jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/list/AbstractMultiGridView.java, jbpm-wb-common/jbpm-wb-common-client/src/test/java/org/jbpm/workbench/common/client/list/AbstractMultiGridPresenterTest.java, jbpm-wb-common/jbpm-wb-common-client/src/test/java/org/jbpm/workbench/common/client/list/AbstractMultiGridViewTest.java
depends on https://github.com/kiegroup/appformer/pull/789.
Only store grid preferences(column arrangement) when save filter operation is performed. Only load stored grid preferences when a saved filter is loaded.
=> JBPM-8742: Link column preferences with saved filter

jbpm-wb-integration/jbpm-wb-integration-backend/pom.xml
This is a change for having always directory for Errai Wildfly unpacked distribution to be on the same name as original wildfly distribution as Errai just repackaged it so naming directory to that version is not confusing
=> fixed real directory for Errai Wildfly distribution

jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/java/org/jbpm/workbench/ks/integration/KieServerDataSetProvider.java, jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/test/java/org/jbpm/workbench/ks/integration/KieServerDataSetProviderTest.java
RHPAM-3292: KIE Server data set editor fails with 'Java Runtime Exception' when trying to hit the Test button second time
--
The root cause for this issue was that columns were not added to the def when doing the first query execution from the dataset editor.
The solution is add the columns to the dataset definition.
=> RHPAM-3292: KIE Server data set editor fails

jbpm-wb-integration/jbpm-wb-integration-backend/src/main/resources/WorkDefinition.wid
**JIRA**: [JBPM-9601](https://issues.redhat.com/browse/JBPM-9601)
**Business Central**: [WAR](https://drive.google.com/file/d/1Yy6azr5QxYlITlTH0caHS0st_uBbx83P/view?usp=sharing)
Hi @romartin, @LuboTerifaj, there is an update of Case Project WID file. It adds only Business Rule and Decision tasks as discussed.
<details>
<summary>
</summary>
* <b>an upstream build</b> please …
=> JBPM-9601: Stunner - Business Rule and Decision tasks are missing in Case Project by default

jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/test/java/org/jbpm/workbench/ks/integration/KieServerQueryDefinitionLoaderTest.java
**[JBPM-9626](https://issues.redhat.com/browse/JBPM-9626)**: Create test case for Long running queries at Kie server startup
=> [JBPM-9626] - Create test case for Long running queries at Kie server startup

jbpm-wb-forms/jbpm-wb-forms-api/src/main/java/org/jbpm/workbench/forms/service/providing/ProcessRenderingSettings.java, jbpm-wb-forms/jbpm-wb-forms-api/src/main/java/org/jbpm/workbench/forms/service/providing/RenderingSettings.java, jbpm-wb-forms/jbpm-wb-forms-api/src/main/java/org/jbpm/workbench/forms/service/providing/TaskRenderingSettings.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/FormServiceEntryPointImpl.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/main/java/org/jbpm/workbench/forms/display/backend/provider/ProcessFormsValuesProcessor.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/AbstractFormsValuesProcessorTest.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/ProcessFormsValuesProcessorTest.java, jbpm-wb-forms/jbpm-wb-forms-backend/src/test/java/org/jbpm/workbench/forms/display/backend/provider/TaskFormValuesProcessorTest.java
* Added tags to Display settings
**JIRA**: 
[AF-2811](https://issues.redhat.com/browse/AF-2811)
[RHPAM-3047](https://issues.redhat.com/browse/RHPAM-3047)
<details>
<summary>
</summary>
</details>
=> AF-2811: Required Process Variable Tags shouldn't be accepted in forms when empty

jbpm-wb-showcase/pom.xml
**JIRA**: [KOGITO-5016](https://issues.redhat.com/browse/KOGITO-5016)
**Parent Pull Request**:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1637
<details>
<summary>
</summary>
</details>
=> KOGITO-5016: Remove Kogito-related modules from v7 stream

jbpm-wb-showcase/pom.xml
Hi @mareknovotny, @mbiarnes, @romartin, @jomarko it is cherry-pick of https://github.com/kiegroup/jbpm-wb/pull/1513
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1771
* https://github.com/kiegroup/kie-wb-distributions/pull/1129
* https://github.com/kiegroup/jbpm-wb/pull/1515
* https://github.com/kiegroup/kie-wb-common/pull/3685
<details>
<summary>
</summary>
* <b>an …
=> [7.59.x] JBPM-9896 - Fix dependency for compilation Stunner on JDK 11 to JRE 8 

jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml, jbpm-wb-showcase/pom.xml
[https://issues.redhat.com/browse/JBPM-9899](JBPM-9899)
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
=> [7.59.x]JBPM-9899 JBPM WB IT tests fails

jbpm-wb-showcase/pom.xml
**JIRA**:
https://issues.redhat.com/browse/AF-2884
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1777
From the dependency tree `woodstox-core` and `woodstox-core-asl` are in conflict
```
...
...
...
[INFO] +- org.apache.chemistry.opencmis:chemistry-opencmis-client-impl:jar:0.14.0:runtime
[INFO] |  +- org.apache.chemistry.opencmis:chemistry-opencmis-client-api:jar:0.14.0:runtime
[INFO] |  +- org.apache.cxf:cxf-rt-frontend-jaxws:jar:3.3.9:runtime
[INFO] |  |  +- xml-resolver:xml-resolver:jar:1.2:runtime
[INFO] |  |  +- org.apache.cxf:cxf-core:jar:3.3.9:runtime
[INFO] |  |  |  \- com.fasterxml.woodstox:woodstox-core:jar:5.0.3:runtime
...
...
...
[INFO] +- …
```
=> [AF-2884] upgrading opencmis version to 0.14.0

jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/java/org/jbpm/workbench/ks/integration/KieServerIntegration.java
https://issues.redhat.com/browse/BAPL-2291
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1975
- https://github.com/kiegroup/droolsjbpm-integration/pull/2786
- https://github.com/kiegroup/kie-wb-playground/pull/129
- https://github.com/kiegroup/kie-wb-common/pull/3740
- https://github.com/kiegroup/jbpm-wb/pull/1547
- https://github.com/kiegroup/kie-wb-distributions/pull/1163
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to …
=> [7.67.x-blue] BAPL-2291 Remove PLANNING capability

jbpm-wb-process-runtime/jbpm-wb-process-runtime-client/src/test/java/org/jbpm/workbench/pr/client/editors/instance/list/ProcessInstanceListBasicFiltersPresenterTest.java
The test in `org.jbpm.workbench.pr.client.editors.instance.list.ProcessInstanceListBasicFiltersPresenterTest#testSlaComplianceFilters` can fail due to a different iteration order of `HashMap`. The failure is presented as follows:
`java.lang.AssertionError: `
`Actual and expected have the same elements but not in the same order, at index 0 actual element was:`
`<MapEntry[key="1", value="SlaPending"]>`
`whereas expected element was:`
` <0=SlaNA>`
The initialization location of the that `HashMap` is `org.jbpm.workbench.common.client.util.SlaStatusConverter.getSLAComplianceAliasMap(SlaStatusConverter.java:72)`
`Map<String, String> aliasMap = new HashMap();`
The specification about `HashMap` says that "this class makes no guarantees as to the order of the map; in particular, it does not …
=> Use containsOnly instead of containsExactly in ProcessInstanceListBasicFiltersPresenterTest

jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/java/org/jbpm/workbench/ks/integration/DateColumnFilterFactory.java, jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/java/org/jbpm/workbench/ks/integration/KieServerDataSetProvider.java, jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/test/java/org/jbpm/workbench/ks/integration/DateColumnFilterFactoryTest.java, jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/test/java/org/jbpm/workbench/ks/integration/KieServerDataSetProviderTest.java
[JBPM-10167](https://issues.redhat.com/browse/JBPM-10167)
*Date filter is not working as expected*
In remote datasets the date filter is generate as an `COLUMN = {value selected by user}`. It does not work for dates. With this change we generate a BETWEEN operator for dates only and a suitable interval of dates so the correct values are generated.
=> RHPAM-4664: Date filter is not working as expected

jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/java/org/jbpm/workbench/ks/integration/KieServerQueryDefinitionLoader.java, jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/resources/default-query-definitions-strict.json, jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/test/java/org/jbpm/workbench/ks/integration/KieServerQueryDefinitionLoaderStrictModeTest.java, jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/test/java/org/jbpm/workbench/ks/integration/KieServerQueryDefinitionLoaderTest.java
Introducing a new environment variable `jbpm.wb.querymode` with possible values DEFAULT or STRICT.
If used Strict mode, the queries will be filtered.
By default it'll continue behave as before, without filtering the queries.
=> RHPAM-4889: using a feature flag to enable/disable strict mode.

jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/java/org/jbpm/workbench/ks/integration/KieServerQueryDefinitionLoader.java, jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/resources/default-query-definitions-strict.json, jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/test/java/org/jbpm/workbench/ks/integration/KieServerQueryDefinitionLoaderStrictModeTest.java, jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/test/java/org/jbpm/workbench/ks/integration/KieServerQueryDefinitionLoaderTest.java
Backport of https://github.com/kiegroup/jbpm-wb/pull/1607  to 7.67.x-blue
@porcelli @gmunozfe @tomasdavidorg @martinweiler @baldimir 
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions …
=> [7.67.x-blue] RHPAM-4889: adjustments to make it easier to consume from openshift env vars

jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/java/org/jbpm/workbench/ks/integration/KieServerQueryDefinitionLoader.java, jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/resources/default-query-definitions-strict.json, jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/test/java/org/jbpm/workbench/ks/integration/KieServerQueryDefinitionLoaderStrictModeTest.java, jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/test/java/org/jbpm/workbench/ks/integration/KieServerQueryDefinitionLoaderTest.java
[RHPAM-4889](https://issues.redhat.com/browse/RHPAM-4889)
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the …
=> [RHPAM-4889] - adjustments to make it easier to consume from openshift env vars
